/**
 * Curated certification / regulatory rules (benchmark data).
 * Instruments, notification numbers and dates were compiled from bis.gov.in
 * (Products under Compulsory Certification), BEE, MoP, CEA and MHI pages on
 * 2026-09-25. None is marked VERIFIED, so the engine caps every match at
 * "Potentially applicable" until an administrator verifies the rule.
 */
import type { CertificationRule, SourceRef } from '../../../shared/knowledge';
import { MOP_EVCI_2024, RETRIEVED_AT, UNVERIFIED } from './standards';

const BIS_SCHEME_I: SourceRef = {
  name: 'BIS — Products under compulsory certification (Scheme-I)',
  url: 'https://www.bis.gov.in/product-certification/products-under-compulsory-certification/',
  retrievedAt: RETRIEVED_AT,
  sourceType: 'GOVERNMENT_PORTAL',
};

const BIS_SCHEME_II: SourceRef = {
  name: 'BIS — Products under compulsory registration (Scheme-II, CRS)',
  url: 'https://www.bis.gov.in/product-certification/products-under-compulsory-certification/',
  retrievedAt: RETRIEVED_AT,
  sourceType: 'GOVERNMENT_PORTAL',
};

const rule = (r: Omit<CertificationRule, 'verification' | 'lifecycle' | 'dataOrigin'>): CertificationRule => ({
  ...r,
  dataOrigin: 'CURATED_PUBLIC_REFERENCE',
  verification: UNVERIFIED,
  lifecycle: 'PUBLISHED',
});

export const CERTIFICATION_RULES: CertificationRule[] = [
  // --- EV charging
  rule({
    id: 'mop-evci-guidelines-2024',
    title: 'MoP EV charging infrastructure guidelines — type testing of EV supply equipment',
    scheme: 'REGULATORY_REQUIREMENT',
    authority: 'Ministry of Power, Government of India',
    instrument: 'Guidelines for Installation and Operation of Electric Vehicle Charging Infrastructure-2024 (No. 12/2/2018-EV, 17 September 2024)',
    standardIds: ['is-17017-1', 'is-17017-2-2', 'is-17017-23', 'is-17017-24', 'is-17017-2-3', 'is-17017-22-1', 'is-17017-25', 'is-17017-31'],
    productCategories: ['ev-charging-equipment', 'ev-ac-charger', 'ev-dc-charger', 'ev-lev-charger'],
    conditionTermsAny: ['public charging', 'public charging station', 'charging station', 'public', 'charging infrastructure', 'parking'],
    conditionDescription: 'The equipment is for public / commercial EV charging infrastructure covered by the guidelines.',
    classificationWhenMatched: 'POTENTIALLY_APPLICABLE',
    explanation:
      'The 2024 guidelines supersede earlier MoP versions and require each EV supply equipment model to be type-tested at a NABL-accredited laboratory against the standards listed in Annexure I (for example IS 17017 (Part 1) and IS 17017 (Part 2/Sec 2) for AC parkbay charging).',
    source: MOP_EVCI_2024,
    effectiveDate: '2024-09-17',
  }),
  rule({
    id: 'cea-safety-regulations-2023-ev',
    title: 'CEA Safety Regulations — additional safety requirements for EV charging stations',
    scheme: 'REGULATORY_REQUIREMENT',
    authority: 'Central Electricity Authority',
    instrument: 'CEA (Measures relating to Safety and Electric Supply) Regulations, 2023 — Chapter XI, Regulations 123–128 (notified 8 June 2023)',
    standardIds: ['is-17017-1', 'is-17017-23', 'is-17017-22-1'],
    productCategories: ['ev-charging-equipment', 'ev-ac-charger', 'ev-dc-charger', 'ev-lev-charger'],
    conditionTermsAny: ['charging station', 'installation', 'install', 'installed', 'public', 'site'],
    conditionDescription: 'The procurement includes installation of an EV charging station.',
    classificationWhenMatched: 'POTENTIALLY_APPLICABLE',
    explanation:
      'Chapter XI sets additional safety requirements for EV charging stations, including socket-outlets at least 800 mm above ground, no adaptors or extension leads, a dedicated sub-circuit with overcurrent protection, earth-continuity monitoring, halogen-free fire-retardant EVSE enclosures, and record keeping.',
    source: {
      name: 'CEA (Measures relating to Safety and Electric Supply) Regulations, 2023',
      url: 'https://cea.nic.in/wp-content/uploads/regulations_cpt/2023/06/pdf_100_183_English-1.pdf',
      retrievedAt: RETRIEVED_AT,
      sourceType: 'GAZETTE_NOTIFICATION',
    },
    effectiveDate: '2023-06-08',
  }),
  rule({
    id: 'ev-no-compulsory-bis',
    title: 'BIS compulsory certification for EV supply equipment',
    scheme: 'BIS_PRODUCT_CERTIFICATION',
    authority: 'Bureau of Indian Standards',
    instrument: 'BIS lists of products under compulsory certification (Scheme-I, Scheme-II, Scheme-X, upcoming QCOs) — checked 25 September 2026',
    standardIds: ['is-17017-1', 'is-17017-23', 'is-17017-22-1', 'is-17017-25', 'is-17017-31'],
    productCategories: ['ev-charging-equipment', 'ev-ac-charger', 'ev-dc-charger', 'ev-lev-charger'],
    conditionTermsAny: [],
    conditionDescription: 'Applies to EV supply equipment covered by the IS 17017 series.',
    classificationWhenMatched: 'NOT_DETECTED',
    explanation:
      'As of 25 September 2026 the IS 17017 series did not appear on the BIS lists of products under compulsory certification. The Machinery and Electrical Equipment Safety (Omnibus Technical Regulation) Order, 2024, which would have covered power semiconductor converters, was withdrawn on 16 January 2026. Claims that BIS certification is mandatory for EV chargers should be checked against the current official list.',
    source: BIS_SCHEME_I,
  }),

  // --- Construction
  rule({
    id: 'qco-cement-2003',
    title: 'Cement (Quality Control) Order — compulsory BIS certification',
    scheme: 'QUALITY_CONTROL_ORDER',
    authority: 'Government of India (Quality Control Order under the BIS framework)',
    instrument: 'Cement (Quality Control) Order, 2003 — S.O. 191(E), 17 February 2003',
    standardIds: ['is-269', 'is-1489-1'],
    productCategories: ['portland-cement', 'ppc-cement'],
    conditionTermsAny: [],
    conditionDescription: 'Cement conforming to the covered Indian Standards.',
    classificationWhenMatched: 'APPLICABLE',
    explanation: 'Covered cements must carry the BIS Standard Mark under a licence (Scheme-I product certification).',
    source: BIS_SCHEME_I,
    effectiveDate: '2003-02-17',
  }),
  rule({
    id: 'qco-steel-2024',
    title: 'Steel and Steel Products (Quality Control) Order — compulsory BIS certification',
    scheme: 'QUALITY_CONTROL_ORDER',
    authority: 'Government of India (Quality Control Order under the BIS framework)',
    instrument: 'Steel and Steel Products (Quality Control) Order, 2024 — S.O. 3716(E), 29 August 2024, as amended by S.O. 5134(E) (2025) and S.O. 3300(E) (2026)',
    standardIds: ['is-1786', 'is-2062'],
    productCategories: ['tmt-bars', 'structural-steel'],
    conditionTermsAny: [],
    conditionDescription: 'Steel products conforming to the covered Indian Standards.',
    classificationWhenMatched: 'APPLICABLE',
    explanation: 'Covered steel products must carry the BIS Standard Mark under a licence.',
    source: BIS_SCHEME_I,
    effectiveDate: '2024-08-29',
  }),

  // --- Electrical
  rule({
    id: 'qco-electrical-accessories-2003',
    title: 'Electrical Wires, Cables, Appliances and Protection Devices and Accessories (Quality Control) Order',
    scheme: 'QUALITY_CONTROL_ORDER',
    authority: 'Government of India (Quality Control Order under the BIS framework)',
    instrument: 'Electrical Wires, Cables, Appliances and Protection Devices and Accessories (Quality Control) Order, 2003 — S.O. 189(E), 17 February 2003 (as amended)',
    standardIds: ['is-694', 'is-12640-1', 'is-12640-2', 'is-iec-60898-1'],
    productCategories: ['pvc-cable', 'protection-devices'],
    conditionTermsAny: [],
    conditionDescription: 'Products conforming to the covered Indian Standards.',
    classificationWhenMatched: 'APPLICABLE',
    explanation: 'Covered products must carry the BIS Standard Mark under a licence (Scheme-I).',
    source: BIS_SCHEME_I,
    effectiveDate: '2003-02-17',
  }),
  rule({
    id: 'qco-cables-2020',
    title: 'Cables (Quality Control) Order — compulsory BIS certification',
    scheme: 'QUALITY_CONTROL_ORDER',
    authority: 'Government of India (Quality Control Order under the BIS framework)',
    instrument: 'Cables (Quality Control) Order, 2020 — S.O. 280(E), 21 January 2020',
    standardIds: ['is-1554-1', 'is-7098-1'],
    productCategories: ['power-cable'],
    conditionTermsAny: [],
    conditionDescription: 'Cables conforming to the covered Indian Standards. The QCO list still references IS 7098 (Part 1) : 1988.',
    classificationWhenMatched: 'APPLICABLE',
    explanation: 'Covered cables must carry the BIS Standard Mark under a licence. Confirm which edition of IS 7098 (Part 1) the order currently references.',
    source: BIS_SCHEME_I,
    effectiveDate: '2020-01-21',
  }),
  rule({
    id: 'qco-transformers-2015',
    title: 'Electrical Transformers (Quality Control) Order — compulsory BIS certification',
    scheme: 'QUALITY_CONTROL_ORDER',
    authority: 'Government of India (Quality Control Order under the BIS framework)',
    instrument: 'Electrical Transformers (Quality Control) Order, 2015 — S.O. 1221(E), 7 May 2015',
    standardIds: ['is-1180-1'],
    productCategories: ['distribution-transformer'],
    conditionTermsAny: [],
    conditionDescription: 'Distribution transformers conforming to IS 1180 (Part 1).',
    classificationWhenMatched: 'APPLICABLE',
    explanation: 'Covered distribution transformers must carry the BIS Standard Mark under a licence.',
    source: BIS_SCHEME_I,
    effectiveDate: '2015-05-07',
  }),
  rule({
    id: 'bee-distribution-transformer',
    title: 'BEE star labelling — distribution transformers (mandatory)',
    scheme: 'ENERGY_LABELLING',
    authority: 'Bureau of Energy Efficiency',
    instrument: 'BEE Standards & Labelling programme — distribution transformer listed as a mandatory appliance',
    standardIds: ['is-1180-1'],
    productCategories: ['distribution-transformer'],
    conditionTermsAny: [],
    conditionDescription: 'Distribution transformers within the scope of the BEE schedule.',
    classificationWhenMatched: 'APPLICABLE',
    explanation: 'BEE lists distribution transformers under mandatory star labelling; the star level should be specified in the tender.',
    source: { name: 'Bureau of Energy Efficiency — Standards & Labelling', url: 'https://beeindia.gov.in/', retrievedAt: RETRIEVED_AT, sourceType: 'GOVERNMENT_PORTAL' },
  }),
  rule({
    id: 'qco-induction-motors-2017',
    title: 'Energy Efficient Induction Motors (Quality Control) Order',
    scheme: 'QUALITY_CONTROL_ORDER',
    authority: 'Government of India (Quality Control Order under the BIS framework)',
    instrument: 'Energy Efficient Induction Motors – Three Phase Squirrel Cage (Quality Control) Order, 2017 — S.O. 178(E), 18 January 2017, amended by S.O. 3207(E), 29 September 2017',
    standardIds: ['is-12615'],
    productCategories: ['induction-motor'],
    conditionTermsAny: ['three phase', 'three-phase', '3 phase', '3-phase', 'squirrel cage', 'induction motor'],
    conditionDescription: 'Three-phase squirrel-cage induction motors within the scope of the order.',
    classificationWhenMatched: 'APPLICABLE',
    explanation: 'Covered motors must carry the BIS Standard Mark under a licence. The date from which the order refers to IS 12615 : 2026 is not verified.',
    source: BIS_SCHEME_I,
    effectiveDate: '2017-01-18',
  }),
  rule({
    id: 'pumps-no-qco',
    title: 'Compulsory certification for agricultural and water supply pumps',
    scheme: 'QUALITY_CONTROL_ORDER',
    authority: 'Bureau of Indian Standards',
    instrument: 'BIS lists of products under compulsory certification — checked 25 September 2026',
    standardIds: ['is-8034', 'is-9079', 'is-14220', 'is-6595-1'],
    productCategories: ['submersible-pumpset', 'monoset-pump', 'openwell-submersible', 'centrifugal-pump'],
    conditionTermsAny: [],
    conditionDescription: 'Pumps covered by the listed Indian Standards.',
    classificationWhenMatched: 'NOT_DETECTED',
    explanation:
      'No pump Quality Control Order appeared on the BIS lists as of 25 September 2026 (the Omnibus Technical Regulation 2024 that covered pumps was withdrawn). Voluntary ISI certification (Scheme-I) exists, and BEE labelling for agricultural pumpsets is voluntary; a purchaser may choose to require either.',
    source: BIS_SCHEME_I,
  }),

  // --- Electronics & renewables
  rule({
    id: 'crs-meity-2021',
    title: 'Compulsory Registration Scheme — lithium cells and batteries',
    scheme: 'BIS_COMPULSORY_REGISTRATION',
    authority: 'Ministry of Electronics and Information Technology',
    instrument: 'Electronics and Information Technology Goods (Requirements for Compulsory Registration) Order, 2021',
    standardIds: ['is-16046-2'],
    productCategories: ['li-ion-battery'],
    conditionTermsAny: ['portable', 'sealed', 'battery', 'cell'],
    conditionDescription: 'Portable sealed lithium secondary cells/batteries within the order scope.',
    classificationWhenMatched: 'APPLICABLE',
    explanation: 'Covered products must be registered with BIS under the Compulsory Registration Scheme (Scheme-II) before sale.',
    source: BIS_SCHEME_II,
  }),
  rule({
    id: 'crs-mnre-solar-2017',
    title: 'Compulsory Registration — solar photovoltaic modules',
    scheme: 'BIS_COMPULSORY_REGISTRATION',
    authority: 'Ministry of New and Renewable Energy',
    instrument: 'Solar Photovoltaics, Systems, Devices and Components Goods (Requirements for Compulsory Registration) Order, 2017 — S.O. 2920(E), 30 August 2017 (as amended)',
    standardIds: ['is-14286-1', 'is-iec-61730-1'],
    productCategories: ['solar-pv-module'],
    conditionTermsAny: [],
    conditionDescription: 'PV modules within the order scope.',
    classificationWhenMatched: 'APPLICABLE',
    explanation: 'Covered PV modules must be registered with BIS under the Compulsory Registration Scheme before sale.',
    source: BIS_SCHEME_II,
    effectiveDate: '2017-08-30',
  }),
];
