/**
 * FiiSpec curated benchmark dataset — standards.
 *
 * Designations, titles, editions, IEC/ISO relations and supersession were
 * compiled from public BIS listings (BIS e-Sale portal, BIS compendia and
 * Public.Resource.org copies) on 2026-09-25. Scope texts are short curated
 * paraphrases, NOT the official text. No record is marked VERIFIED: an
 * administrator must verify each record against the current BIS catalogue.
 * This is a small benchmark subset and does not represent BIS coverage.
 */
import type { SourceRef, StandardRecord, Verification } from '../../../shared/knowledge';

export const RETRIEVED_AT = '2026-09-25';

export const bisPortal = (query: string, note?: string): SourceRef => ({
  name: 'BIS e-Sale portal — standard listing',
  url: `https://standardsbis.bsbedge.com/BIS_SearchStandard.aspx?Standard_Number=${encodeURIComponent(query)}`,
  retrievedAt: RETRIEVED_AT,
  sourceType: 'BIS_CATALOGUE',
  ...(note ? { note } : {}),
});

export const BIS_EV_COMPENDIUM: SourceRef = {
  name: 'BIS compendium of Indian Standards on electric vehicles (June 2025)',
  url: 'https://www.services.bis.gov.in/tmp/compendium_2025-06-02-05-05-20.pdf',
  retrievedAt: RETRIEVED_AT,
  sourceType: 'BIS_PUBLIC_DOCUMENT',
};

export const MOP_EVCI_2024: SourceRef = {
  name: 'Ministry of Power — Guidelines for Installation and Operation of Electric Vehicle Charging Infrastructure-2024 (No. 12/2/2018-EV, 17 Sep 2024)',
  url: 'https://powermin.gov.in/sites/default/files/Guidelines_and_Standards_for_EVCI_dated_17_09_2024.pdf',
  retrievedAt: RETRIEVED_AT,
  sourceType: 'GOVERNMENT_PORTAL',
};

export const UNVERIFIED: Verification = {
  status: 'UNVERIFIED',
  note: 'Compiled from public BIS listings on 2026-09-25 (automated research). Pending verification by a FiiSpec administrator against the current BIS catalogue.',
};

const TITLE_NOTE: Verification = {
  status: 'UNVERIFIED',
  note: 'Supersession confirmed from the BIS portal listing on 2026-09-25; the title is given as commonly cited and has not been re-verified.',
};

type StandardInput = Omit<StandardRecord, 'supersedes' | 'versionHistory' | 'amendments' | 'amendmentDataStatus' | 'evidenceReferences' | 'dataOrigin' | 'verification' | 'lifecycle' | 'keywords' | 'productTypes'> &
  Partial<Pick<StandardRecord, 'supersedes' | 'versionHistory' | 'amendments' | 'amendmentDataStatus' | 'evidenceReferences' | 'verification' | 'keywords' | 'productTypes'>>;

function std(input: StandardInput): StandardRecord {
  return {
    supersedes: [],
    versionHistory: input.publicationYear
      ? [{ designation: `${input.standardNumber} : ${input.publicationYear}`, year: input.publicationYear, label: input.edition ?? 'Current edition', status: input.status }]
      : [],
    amendments: [],
    amendmentDataStatus: 'NOT_INDEXED',
    evidenceReferences: [],
    keywords: [],
    productTypes: [],
    verification: UNVERIFIED,
    dataOrigin: 'CURATED_PUBLIC_REFERENCE',
    lifecycle: 'PUBLISHED',
    ...input,
  };
}

const portalAmendment = (standard: string, n: number) => ({
  id: `amd-${n}`,
  number: n,
  summary: `Amendment No. ${n} is listed for ${standard} on the BIS e-Sale portal. Its content is not indexed in FiiSpec.`,
  source: bisPortal(standard.replace(/\s*:.*/, '')),
  verification: UNVERIFIED,
});

export const STANDARDS: StandardRecord[] = [
  // ---------------------------------------------------------------- EV charging
  std({
    id: 'is-17017-1',
    standardNumber: 'IS 17017 (Part 1)',
    baseNumber: '17017',
    part: '1',
    prefix: 'IS',
    title: 'Electric Vehicle Conductive Charging System — Part 1: General Requirements',
    sector: 'ELECTROTECHNICAL_EV',
    kind: 'SYSTEM',
    scope:
      'General requirements for conductive charging systems that supply electric road vehicles, covering charging modes, protection against electric shock, connection between supply and vehicle, and equipment characteristics. Curated summary; the Indian standard corresponds to IEC 61851-1 : 2017 with modifications (only Type 2 and Systems A and C retained; voltages as per IS 12360).',
    status: 'CURRENT',
    edition: 'First edition',
    publicationYear: 2018,
    adoptedFrom: 'IEC 61851-1:2017',
    keywords: ['ev charging', 'electric vehicle', 'conductive charging', 'charging station', 'evse', 'charging mode', 'ac charging', 'charge point', 'mode 3', 'charger', 'public charging'],
    productTypes: ['ev-charging-equipment', 'ev-ac-charger', 'ev-dc-charger'],
    amendmentDataStatus: 'INDEXED',
    source: bisPortal('IS 17017', 'Listed as active with 0 amendments (portal, 2026-09-25).'),
    evidenceReferences: [
      { name: 'Public.Resource.org copy of IS 17017 (Part 1) : 2018 (foreword)', url: 'https://archive.org/details/gov.in.is.17017.1.2018', retrievedAt: RETRIEVED_AT, sourceType: 'SECONDARY' },
      BIS_EV_COMPENDIUM,
    ],
  }),
  std({
    id: 'is-17017-2-1',
    standardNumber: 'IS 17017 (Part 2/Sec 1)',
    baseNumber: '17017',
    part: '2',
    section: '1',
    prefix: 'IS',
    title: 'Electric Vehicle Conductive Charging System — Part 2: Plugs, Socket-Outlets, Vehicle Connectors and Vehicle Inlets — Section 1: General Requirements',
    sector: 'ELECTROTECHNICAL_EV',
    kind: 'COMPONENT',
    scope:
      'General requirements for plugs, socket-outlets, vehicle connectors and vehicle inlets used for conductive charging of electric vehicles, up to 690 V a.c./250 A and 1500 V d.c./200 A. Curated summary; most requirements correspond to IEC 62196-1 : 2014, with India-specific provisions.',
    status: 'CURRENT',
    publicationYear: 2020,
    adoptedFrom: 'IEC 62196-1:2014',
    keywords: ['vehicle connector', 'vehicle inlet', 'socket-outlet', 'plug', 'charging connector', 'connector'],
    productTypes: ['ev-connector'],
    source: bisPortal('IS 17017'),
    evidenceReferences: [BIS_EV_COMPENDIUM],
  }),
  std({
    id: 'is-17017-2-2',
    standardNumber: 'IS 17017 (Part 2/Sec 2)',
    baseNumber: '17017',
    part: '2',
    section: '2',
    prefix: 'IS',
    title: 'Electric Vehicle Conductive Charging System — Part 2: Plugs, Socket-Outlets, Vehicle Connectors and Vehicle Inlets — Section 2: Dimensional Compatibility and Interchangeability Requirements for a.c. Pin and Contact-Tube Accessories',
    sector: 'ELECTROTECHNICAL_EV',
    kind: 'COMPONENT',
    scope:
      'Dimensional compatibility and interchangeability requirements for a.c. pin and contact-tube charging accessories (the Type 2 family). Curated summary; based on IEC 62196-2 : 2016 with modifications.',
    status: 'CURRENT',
    publicationYear: 2020,
    adoptedFrom: 'IEC 62196-2:2016',
    keywords: ['type 2', 'ac connector', 'contact-tube', 'pin', 'interchangeability', 'socket-outlet', 'connector'],
    productTypes: ['ev-connector'],
    source: bisPortal('IS 17017'),
    evidenceReferences: [BIS_EV_COMPENDIUM, MOP_EVCI_2024],
  }),
  std({
    id: 'is-17017-2-3',
    standardNumber: 'IS 17017 (Part 2/Sec 3)',
    baseNumber: '17017',
    part: '2',
    section: '3',
    prefix: 'IS',
    title: 'Electric Vehicle Conductive Charging System — Part 2: Plugs, Socket-Outlets, Vehicle Connectors and Vehicle Inlets — Section 3: Dimensional Compatibility and Interchangeability Requirements for d.c. and a.c./d.c. Pin and Contact-Tube Vehicle Couplers',
    sector: 'ELECTROTECHNICAL_EV',
    kind: 'COMPONENT',
    scope:
      'Dimensional compatibility and interchangeability requirements for d.c. and combined a.c./d.c. vehicle couplers (such as the combined charging system family). Curated summary; based on IEC 62196-3 : 2014 with modifications.',
    status: 'CURRENT',
    publicationYear: 2020,
    adoptedFrom: 'IEC 62196-3:2014',
    keywords: ['dc connector', 'ccs2', 'combined charging', 'vehicle coupler', 'dc charging', 'connector'],
    productTypes: ['ev-connector'],
    source: bisPortal('IS 17017'),
    evidenceReferences: [BIS_EV_COMPENDIUM, MOP_EVCI_2024],
  }),
  std({
    id: 'is-17017-2-6',
    standardNumber: 'IS 17017 (Part 2/Sec 6)',
    baseNumber: '17017',
    part: '2',
    section: '6',
    prefix: 'IS',
    title: 'Electric Vehicle Conductive Charging System — Part 2: Plugs, Socket-Outlets, Vehicle Connectors and Vehicle Inlets — Section 6: Dimensional Compatibility Requirements for DC Pin and Contact-Tube Vehicle Couplers Intended to be Used for DC EV Supply Equipment where Protection Relies on Electrical Separation',
    sector: 'ELECTROTECHNICAL_EV',
    kind: 'COMPONENT',
    scope: 'Dimensional compatibility requirements for d.c. vehicle couplers used with d.c. supply equipment where protection relies on electrical separation, typically light electric vehicles. Curated summary.',
    status: 'CURRENT',
    publicationYear: 2021,
    keywords: ['light electric vehicle', 'dc coupler', 'electrical separation', 'lev'],
    productTypes: ['ev-connector'],
    source: bisPortal('IS 17017'),
    evidenceReferences: [BIS_EV_COMPENDIUM],
  }),
  std({
    id: 'is-17017-2-7',
    standardNumber: 'IS 17017 (Part 2/Sec 7)',
    baseNumber: '17017',
    part: '2',
    section: '7',
    prefix: 'IS',
    title: 'Electric Vehicle Conductive Charging System — Part 2: Plugs, Socket-Outlets, Vehicle Connectors and Vehicle Inlets — Section 7: Dimensional Compatibility and Interchangeability Requirements for a.c., d.c. and a.c./d.c. Pin and Contact-Tube Vehicle Couplers',
    sector: 'ELECTROTECHNICAL_EV',
    kind: 'COMPONENT',
    scope: 'Dimensional compatibility and interchangeability requirements for a.c., d.c. and combined vehicle couplers where protection relies on electrical separation (light electric vehicle combined charging). Curated summary; IEC basis not verified.',
    status: 'CURRENT',
    publicationYear: 2023,
    keywords: ['light electric vehicle', 'combined coupler', 'lev', 'electrical separation'],
    productTypes: ['ev-connector'],
    source: bisPortal('IS 17017'),
    evidenceReferences: [BIS_EV_COMPENDIUM],
  }),
  std({
    id: 'is-17017-21-1',
    standardNumber: 'IS 17017 (Part 21/Sec 1)',
    baseNumber: '17017',
    part: '21',
    section: '1',
    prefix: 'IS',
    title: 'Electric Vehicle Conductive Charging System — Part 21: Electromagnetic Compatibility (EMC) Requirements — Section 1: On-board Chargers',
    sector: 'ELECTROTECHNICAL_EV',
    kind: 'TEST_METHOD',
    scope: 'Electromagnetic compatibility requirements and tests for on-board chargers of electric vehicles when connected to the supply. Curated summary; the portal lists IEC 61851-21-1 : 2017 as the corresponding standard.',
    status: 'CURRENT',
    publicationYear: 2019,
    adoptedFrom: 'IEC 61851-21-1:2017',
    keywords: ['emc', 'electromagnetic compatibility', 'on-board charger', 'emission', 'immunity'],
    productTypes: [],
    source: bisPortal('IS 17017'),
  }),
  std({
    id: 'is-17017-21-2',
    standardNumber: 'IS 17017 (Part 21/Sec 2)',
    baseNumber: '17017',
    part: '21',
    section: '2',
    prefix: 'IS',
    title: 'Electric Vehicle Conductive Charging System — Part 21: Electromagnetic Compatibility (EMC) Requirements — Section 2: Off-board Chargers',
    sector: 'ELECTROTECHNICAL_EV',
    kind: 'TEST_METHOD',
    scope: 'Electromagnetic compatibility requirements and tests for off-board charging equipment (EV supply equipment). Curated summary; the portal lists IEC 61851-21-2 : 2018 as the corresponding standard.',
    status: 'CURRENT',
    publicationYear: 2019,
    adoptedFrom: 'IEC 61851-21-2:2018',
    keywords: ['emc', 'electromagnetic compatibility', 'off-board charger', 'emission', 'immunity', 'evse'],
    productTypes: [],
    source: bisPortal('IS 17017'),
  }),
  std({
    id: 'is-17017-22-1',
    standardNumber: 'IS 17017 (Part 22/Sec 1)',
    baseNumber: '17017',
    part: '22',
    section: '1',
    prefix: 'IS',
    title: 'Electric Vehicle Conductive Charging Systems — Part 22: A.C. Charging Configurations — Section 1: A.C. Charge Point for Light Electric Vehicle',
    sector: 'ELECTROTECHNICAL_EV',
    kind: 'PRODUCT',
    scope: 'Requirements for a.c. charge points for light electric vehicles (two- and three-wheelers), 240 V a.c., 16 A. Curated summary; developed on the basis of IS 17017 (Part 1) : 2018 with IS/IEC 60309-1 connectors; not IEC-based.',
    status: 'CURRENT',
    publicationYear: 2021,
    keywords: ['light electric vehicle', 'lev', 'ac charge point', 'two wheeler', 'three wheeler', 'e-rickshaw', '16 a', 'charger'],
    productTypes: ['ev-lev-charger'],
    source: bisPortal('IS 17017'),
    evidenceReferences: [BIS_EV_COMPENDIUM, MOP_EVCI_2024],
  }),
  std({
    id: 'is-17017-23',
    standardNumber: 'IS 17017 (Part 23)',
    baseNumber: '17017',
    part: '23',
    prefix: 'IS',
    title: 'Electric Vehicle Conductive Charging System — Part 23: d.c. Electric Vehicle Supply Equipment',
    sector: 'ELECTROTECHNICAL_EV',
    kind: 'PRODUCT',
    scope: 'Requirements for d.c. electric vehicle supply equipment (d.c. chargers) for conductive connection to the vehicle. Curated summary; the 2026 edition corresponds to IEC 61851-23 : 2023 (modified).',
    status: 'CURRENT',
    edition: 'Revision (2026)',
    publicationYear: 2026,
    adoptedFrom: 'IEC 61851-23:2023',
    keywords: ['dc charger', 'dc evse', 'fast charger', 'dc charging', 'ccs2', 'charging station', 'charger'],
    productTypes: ['ev-dc-charger'],
    versionHistory: [
      { designation: 'IS 17017 (Part 23) : 2021', year: 2021, label: 'First edition (based on IEC 61851-23 Ed.2 CDV)', status: 'SUPERSEDED', note: 'The BIS portal lists the 2021 edition as valid up to 06 January 2027 (concurrent running with the 2026 edition).' },
      { designation: 'IS 17017 (Part 23) : 2026', year: 2026, label: 'Revision based on IEC 61851-23 : 2023 (MOD)', status: 'CURRENT' },
    ],
    source: bisPortal('IS 17017', '2021 edition listed as valid up to 06 January 2027.'),
    evidenceReferences: [BIS_EV_COMPENDIUM, MOP_EVCI_2024],
  }),
  std({
    id: 'is-17017-24',
    standardNumber: 'IS 17017 (Part 24)',
    baseNumber: '17017',
    part: '24',
    prefix: 'IS',
    title: 'Electric Vehicle Conductive Charging System — Part 24: Digital Communication between a DC Electric Vehicle Supply Equipment and an Electric Vehicle for Control of DC Charging',
    sector: 'ELECTROTECHNICAL_EV',
    kind: 'COMPONENT',
    scope: 'Digital communication between d.c. EV supply equipment and the electric vehicle for control of d.c. charging. Curated summary; based on IEC 61851-24 Ed.2 CDV with modifications.',
    status: 'CURRENT',
    publicationYear: 2021,
    keywords: ['digital communication', 'dc charging control', 'vehicle communication', 'charging protocol'],
    productTypes: [],
    amendmentDataStatus: 'INDEXED',
    amendments: [portalAmendment('IS 17017 (Part 24) : 2021', 1)],
    source: bisPortal('IS 17017', 'Listed with 1 amendment.'),
  }),
  std({
    id: 'is-17017-25',
    standardNumber: 'IS 17017 (Part 25)',
    baseNumber: '17017',
    part: '25',
    prefix: 'IS',
    title: 'Electric Vehicle Conductive Charging System — Part 25: D.C. EV Supply Equipment where Protection Relies on Electrical Separation',
    sector: 'ELECTROTECHNICAL_EV',
    kind: 'PRODUCT',
    scope: 'Requirements for d.c. EV supply equipment where protection relies on electrical separation, used for light electric vehicle d.c. charging. Curated summary; based on IEC 61851-25 : 2020 with modifications.',
    status: 'CURRENT',
    publicationYear: 2021,
    adoptedFrom: 'IEC 61851-25:2020',
    keywords: ['light electric vehicle', 'lev dc', 'electrical separation', 'dc charger'],
    productTypes: ['ev-lev-charger'],
    source: bisPortal('IS 17017'),
    evidenceReferences: [MOP_EVCI_2024],
  }),
  std({
    id: 'is-17017-30',
    standardNumber: 'IS 17017 (Part 30)',
    baseNumber: '17017',
    part: '30',
    prefix: 'IS',
    title: 'Electric Vehicle Conductive Charging System — Part 30: Dual Gun d.c. Electric Vehicle Supply Equipment',
    sector: 'ELECTROTECHNICAL_EV',
    kind: 'PRODUCT',
    scope: 'Requirements for d.c. EV supply equipment that charges through two charging guns. Curated summary; IEC basis not verified.',
    status: 'CURRENT',
    publicationYear: 2025,
    keywords: ['dual gun', 'dc charger', 'high power charging'],
    productTypes: [],
    source: bisPortal('IS 17017'),
  }),
  std({
    id: 'is-17017-31',
    standardNumber: 'IS 17017 (Part 31)',
    baseNumber: '17017',
    part: '31',
    prefix: 'IS',
    title: 'Electric Vehicle Conductive Charging System — Part 31: a.c. or d.c. EV Supply Equipment where Protection Relies on Electrical Separation',
    sector: 'ELECTROTECHNICAL_EV',
    kind: 'PRODUCT',
    scope: 'Requirements for a.c. or d.c. EV supply equipment where protection relies on electrical separation (light electric vehicle combined charging). Curated summary; IEC basis not verified.',
    status: 'CURRENT',
    publicationYear: 2024,
    keywords: ['light electric vehicle', 'combined charging', 'electrical separation', 'lev'],
    productTypes: ['ev-lev-charger'],
    source: bisPortal('IS 17017'),
    evidenceReferences: [MOP_EVCI_2024],
  }),
  std({
    id: 'is-iso-15118-1',
    standardNumber: 'IS/ISO 15118-1',
    baseNumber: '15118',
    part: '1',
    prefix: 'IS/ISO',
    title: 'Road Vehicles — Vehicle to Grid Communication Interface — Part 1: General Information and Use-case Definition',
    sector: 'ELECTROTECHNICAL_EV',
    kind: 'COMPONENT',
    scope: 'General information and use cases for communication between electric vehicles and EV supply equipment. Curated summary; listed in the BIS EV compendium.',
    status: 'CURRENT',
    publicationYear: 2013,
    adoptedFrom: 'ISO 15118-1',
    keywords: ['vehicle to grid', 'iso 15118', 'plug and charge', 'communication'],
    productTypes: [],
    source: bisPortal('IS/ISO 15118'),
    evidenceReferences: [BIS_EV_COMPENDIUM],
  }),
  std({
    id: 'is-iso-15118-2',
    standardNumber: 'IS/ISO 15118-2',
    baseNumber: '15118',
    part: '2',
    prefix: 'IS/ISO',
    title: 'Road Vehicles — Vehicle to Grid Communication Interface — Part 2: Network and Application Protocol Requirements',
    sector: 'ELECTROTECHNICAL_EV',
    kind: 'COMPONENT',
    scope: 'Network and application protocol requirements for high-level communication between electric vehicles and EV supply equipment. Curated summary; listed in the BIS EV compendium.',
    status: 'CURRENT',
    publicationYear: 2014,
    adoptedFrom: 'ISO 15118-2',
    keywords: ['vehicle to grid', 'iso 15118', 'high level communication', 'communication protocol'],
    productTypes: [],
    source: bisPortal('IS/ISO 15118'),
    evidenceReferences: [BIS_EV_COMPENDIUM, MOP_EVCI_2024],
  }),

  // ------------------------------------------------------- Electrical installation & protection
  std({
    id: 'is-iec-60529',
    standardNumber: 'IS/IEC 60529',
    baseNumber: '60529',
    prefix: 'IS/IEC',
    title: 'Degrees of Protection Provided by Enclosures (IP Code)',
    sector: 'ELECTRICAL',
    kind: 'TEST_METHOD',
    scope: 'Classification of degrees of protection provided by enclosures of electrical equipment against access to hazardous parts and ingress of solid objects and water (the IP code), with the associated tests. Curated summary; identical with IEC 60529 : 2001; reaffirmed 2019.',
    status: 'CURRENT',
    publicationYear: 2001,
    adoptedFrom: 'IEC 60529:2001',
    keywords: ['ip code', 'ingress protection', 'enclosure', 'degree of protection', 'dust', 'water ingress', 'outdoor'],
    productTypes: [],
    supersedes: [{ standardId: 'is-12063', designation: 'IS 12063 : 1987', note: 'The BIS portal lists IS 12063 : 1987 as superseded by IS/IEC 60529 : 2001.' }],
    versionHistory: [
      { designation: 'IS 12063 : 1987', year: 1987, label: 'Earlier Indian standard (superseded)', status: 'SUPERSEDED' },
      { designation: 'IS/IEC 60529 : 2001', year: 2001, label: 'Identical adoption of IEC 60529 : 2001 (reaffirmed 2019)', status: 'CURRENT' },
    ],
    source: bisPortal('IS/IEC 60529'),
  }),
  std({
    id: 'is-12063',
    standardNumber: 'IS 12063',
    baseNumber: '12063',
    prefix: 'IS',
    title: 'Classification of Degrees of Protection Provided by Enclosures of Electrical Equipment',
    sector: 'ELECTRICAL',
    kind: 'TEST_METHOD',
    scope: 'Earlier Indian standard on degrees of protection provided by enclosures. Recorded as superseded by IS/IEC 60529 : 2001.',
    status: 'SUPERSEDED',
    publicationYear: 1987,
    supersededBy: { standardId: 'is-iec-60529', designation: 'IS/IEC 60529 : 2001' },
    keywords: ['ip code', 'enclosure'],
    productTypes: [],
    verification: TITLE_NOTE,
    source: bisPortal('IS 12063', 'Portal: "Superseded by IS/IEC 60529:2001".'),
  }),
  std({
    id: 'is-732',
    standardNumber: 'IS 732',
    baseNumber: '732',
    prefix: 'IS',
    title: 'Code of Practice for Electrical Wiring Installations',
    sector: 'ELECTRICAL',
    kind: 'CODE_OF_PRACTICE',
    scope: 'Code of practice for the design, selection, erection, inspection and testing of electrical wiring installations in buildings and premises. Curated summary; largely based on the IEC 60364 series.',
    status: 'CURRENT',
    edition: 'Fourth Revision',
    publicationYear: 2019,
    keywords: ['wiring installation', 'electrical installation', 'wiring', 'circuit', 'installation', 'inspection and testing'],
    productTypes: ['electrical-installation'],
    versionHistory: [
      { designation: 'IS 732 : 1989', year: 1989, label: 'Third Revision', status: 'SUPERSEDED' },
      { designation: 'IS 732 : 2019', year: 2019, label: 'Fourth Revision', status: 'CURRENT' },
    ],
    source: bisPortal('IS 732'),
  }),
  std({
    id: 'is-3043',
    standardNumber: 'IS 3043',
    baseNumber: '3043',
    prefix: 'IS',
    title: 'Code of Practice for Earthing',
    sector: 'ELECTRICAL',
    kind: 'CODE_OF_PRACTICE',
    scope: 'Code of practice for the earthing of electrical installations and equipment, including earth electrodes, protective conductors and measurement of earth resistance. Curated summary.',
    status: 'CURRENT',
    edition: 'Second Revision',
    publicationYear: 2018,
    keywords: ['earthing', 'earth electrode', 'protective earth', 'earth resistance', 'grounding', 'earth pit'],
    productTypes: ['electrical-installation'],
    versionHistory: [
      { designation: 'IS 3043 : 1966', year: 1966, label: 'First published', status: 'SUPERSEDED' },
      { designation: 'IS 3043 : 1987', year: 1987, label: 'First Revision', status: 'SUPERSEDED' },
      { designation: 'IS 3043 : 2018', year: 2018, label: 'Second Revision', status: 'CURRENT' },
    ],
    source: bisPortal('IS 3043'),
  }),
  std({
    id: 'is-12640-1',
    standardNumber: 'IS 12640 (Part 1)',
    baseNumber: '12640',
    part: '1',
    prefix: 'IS',
    title: 'Residual Current Operated Circuit-Breakers without Integral Overcurrent Protection for Household and Similar Uses (RCCBs) — Part 1: General Rules',
    sector: 'ELECTRICAL',
    kind: 'SAFETY',
    scope: 'Requirements for residual current operated circuit-breakers without integral overcurrent protection (RCCBs) for household and similar uses. Curated summary; corresponds to IEC 61008-1 : 2013.',
    status: 'CURRENT',
    publicationYear: 2024,
    adoptedFrom: 'IEC 61008-1:2013',
    keywords: ['rccb', 'residual current', 'earth leakage', 'rcd', 'protection against electric shock'],
    productTypes: ['protection-devices'],
    versionHistory: [
      { designation: 'IS 12640 (Part 1) : 2016', year: 2016, label: 'Previous edition (inferred from current listing)', status: 'SUPERSEDED' },
      { designation: 'IS 12640 (Part 1) : 2024', year: 2024, label: 'Current edition', status: 'CURRENT' },
    ],
    source: bisPortal('IS 12640'),
  }),
  std({
    id: 'is-12640-2',
    standardNumber: 'IS 12640 (Part 2)',
    baseNumber: '12640',
    part: '2',
    prefix: 'IS',
    title: 'Residual Current Operated Circuit-Breakers with Integral Overcurrent Protection for Household and Similar Uses (RCBOs) — Part 2: General Rules',
    sector: 'ELECTRICAL',
    kind: 'SAFETY',
    scope: 'Requirements for residual current operated circuit-breakers with integral overcurrent protection (RCBOs) for household and similar uses. Curated summary; corresponds to IEC 61009-1 : 2012.',
    status: 'CURRENT',
    edition: 'Second Revision',
    publicationYear: 2016,
    adoptedFrom: 'IEC 61009-1:2012',
    keywords: ['rcbo', 'residual current', 'overcurrent', 'earth leakage'],
    productTypes: ['protection-devices'],
    source: bisPortal('IS 12640'),
  }),
  std({
    id: 'is-iec-60898-1',
    standardNumber: 'IS/IEC 60898-1',
    baseNumber: '60898',
    part: '1',
    prefix: 'IS/IEC',
    title: 'Electrical Accessories — Circuit-Breakers for Overcurrent Protection for Household and Similar Installations — Part 1: Circuit-breakers for a.c. Operation',
    sector: 'ELECTRICAL',
    kind: 'SAFETY',
    scope: 'Requirements for a.c. circuit-breakers (MCBs) for overcurrent protection in household and similar installations. Curated summary; corresponds to IEC 60898-1 : 2015; reaffirmed 2024.',
    status: 'CURRENT',
    edition: 'First Revision',
    publicationYear: 2015,
    adoptedFrom: 'IEC 60898-1:2015',
    keywords: ['mcb', 'miniature circuit breaker', 'overcurrent protection', 'circuit-breaker', 'short circuit'],
    productTypes: ['protection-devices'],
    supersedes: [{ standardId: 'is-8828', designation: 'IS 8828 : 1996', note: 'IS/IEC 60898-1 : 2002 superseded IS 8828 : 1996; the 2015 edition replaced the 2002 edition.' }],
    versionHistory: [
      { designation: 'IS 8828 : 1996', year: 1996, label: 'Earlier Indian standard (superseded)', status: 'SUPERSEDED' },
      { designation: 'IS/IEC 60898-1 : 2002', year: 2002, label: 'First adoption of IEC 60898-1', status: 'SUPERSEDED' },
      { designation: 'IS/IEC 60898-1 : 2015', year: 2015, label: 'First Revision (reaffirmed 2024)', status: 'CURRENT' },
    ],
    source: bisPortal('IS/IEC 60898'),
  }),
  std({
    id: 'is-8828',
    standardNumber: 'IS 8828',
    baseNumber: '8828',
    prefix: 'IS',
    title: 'Electrical Accessories — Circuit Breakers for Overcurrent Protection for Household and Similar Installations',
    sector: 'ELECTRICAL',
    kind: 'SAFETY',
    scope: 'Earlier Indian standard for miniature circuit-breakers. Recorded as superseded by IS/IEC 60898-1.',
    status: 'SUPERSEDED',
    publicationYear: 1996,
    supersededBy: { standardId: 'is-iec-60898-1', designation: 'IS/IEC 60898-1 : 2015' },
    keywords: ['mcb', 'circuit breaker'],
    productTypes: [],
    verification: TITLE_NOTE,
    source: bisPortal('IS 8828', 'QCO list shows IS 8828 "since revised as IS/IEC 60898".'),
  }),
  std({
    id: 'is-1885-17',
    standardNumber: 'IS 1885 (Part 17)',
    baseNumber: '1885',
    part: '17',
    prefix: 'IS',
    title: 'Electrotechnical Vocabulary — Part 17: Switchgear and Controlgear',
    sector: 'ELECTRICAL',
    kind: 'TERMINOLOGY',
    scope: 'Terms and definitions for switchgear and controlgear. Curated summary; corresponds to IEC 60050-441.',
    status: 'CURRENT',
    publicationYear: 2024,
    adoptedFrom: 'IEC 60050-441',
    keywords: ['vocabulary', 'terminology', 'switchgear', 'controlgear', 'definitions'],
    source: bisPortal('IS 1885'),
  }),
  std({
    id: 'is-1885-27',
    standardNumber: 'IS 1885 (Part 27)',
    baseNumber: '1885',
    part: '27',
    prefix: 'IS',
    title: 'Electrotechnical Vocabulary — Part 27: Power Electronics',
    sector: 'ELECTRICAL',
    kind: 'TERMINOLOGY',
    scope: 'Terms and definitions for power electronics, including converters. Curated summary; corresponds to IEC 60050-551.',
    status: 'CURRENT',
    publicationYear: 2008,
    adoptedFrom: 'IEC 60050-551',
    keywords: ['vocabulary', 'terminology', 'power electronics', 'converter', 'definitions'],
    source: bisPortal('IS 1885'),
  }),
  std({
    id: 'is-1885-32',
    standardNumber: 'IS 1885 (Part 32)',
    baseNumber: '1885',
    part: '32',
    prefix: 'IS',
    title: 'Electrotechnical Vocabulary — Part 32: Electric Cables',
    sector: 'ELECTRICAL',
    kind: 'TERMINOLOGY',
    scope: 'Terms and definitions for electric cables. Curated summary; corresponds to IEC 60050-461.',
    status: 'CURRENT',
    publicationYear: 2019,
    adoptedFrom: 'IEC 60050-461',
    keywords: ['vocabulary', 'terminology', 'electric cables', 'definitions'],
    source: bisPortal('IS 1885'),
  }),
  std({
    id: 'is-1885-35',
    standardNumber: 'IS 1885 (Part 35)',
    baseNumber: '1885',
    part: '35',
    prefix: 'IS',
    title: 'Electrotechnical Vocabulary — Part 35: Rotating Machinery',
    sector: 'ELECTRICAL',
    kind: 'TERMINOLOGY',
    scope: 'Terms and definitions for rotating electrical machines. Curated summary; corresponds to IEC 60050-411.',
    status: 'CURRENT',
    publicationYear: 2021,
    adoptedFrom: 'IEC 60050-411',
    keywords: ['vocabulary', 'terminology', 'rotating machinery', 'motor', 'definitions'],
    source: bisPortal('IS 1885'),
  }),
  std({
    id: 'is-1885-38',
    standardNumber: 'IS 1885 (Part 38)',
    baseNumber: '1885',
    part: '38',
    prefix: 'IS',
    title: 'Electrotechnical Vocabulary — Part 38: Power Transformers and Reactors',
    sector: 'ELECTRICAL',
    kind: 'TERMINOLOGY',
    scope: 'Terms and definitions for power transformers and reactors. Curated summary; corresponds to IEC 50-421.',
    status: 'CURRENT',
    publicationYear: 1993,
    keywords: ['vocabulary', 'terminology', 'transformer', 'reactor', 'definitions'],
    source: bisPortal('IS 1885'),
  }),

  // ------------------------------------------------------- Cables
  std({
    id: 'is-694',
    standardNumber: 'IS 694',
    baseNumber: '694',
    prefix: 'IS',
    title: 'Polyvinyl Chloride Insulated Unsheathed and Sheathed Cables/Cords with Rigid and Flexible Conductor for Rated Voltages up to and including 450/750 V',
    sector: 'ELECTRICAL',
    kind: 'PRODUCT',
    scope: 'PVC insulated unsheathed and sheathed cables and cords with rigid or flexible conductors, commonly used for building wiring. Curated summary.',
    status: 'CURRENT',
    edition: 'Fourth Revision',
    publicationYear: 2010,
    keywords: ['pvc insulated', 'cable', 'wire', 'building wire', 'flexible cord', 'house wire', 'copper conductor'],
    productTypes: ['pvc-cable'],
    verification: {
      status: 'UNVERIFIED',
      note: 'Title as on the published text (450/750 V). The BIS portal and QCO list give the title as "…up to and including 1100 V"; the discrepancy is unresolved and must be checked.',
    },
    source: bisPortal('IS 694', 'Reaffirmed 2020.'),
  }),
  std({
    id: 'is-1554-1',
    standardNumber: 'IS 1554 (Part 1)',
    baseNumber: '1554',
    part: '1',
    prefix: 'IS',
    title: 'PVC Insulated (Heavy Duty) Electric Cables — Part 1: For Working Voltages up to and including 1 100 V',
    sector: 'ELECTRICAL',
    kind: 'PRODUCT',
    scope: 'PVC insulated heavy-duty power cables for working voltages up to and including 1 100 V. Curated summary; reaffirmed 2020.',
    status: 'CURRENT',
    publicationYear: 1988,
    keywords: ['pvc power cable', 'heavy duty cable', 'armoured cable', '1100 v', 'lt cable', 'power cable'],
    productTypes: ['power-cable'],
    source: bisPortal('IS 1554'),
  }),
  std({
    id: 'is-7098-1',
    standardNumber: 'IS 7098 (Part 1)',
    baseNumber: '7098',
    part: '1',
    prefix: 'IS',
    title: 'Crosslinked Polyethylene Insulated Thermoplastic Sheathed Cables — Specification — Part 1: For Working Voltages up to and including 1 100 Volts',
    sector: 'ELECTRICAL',
    kind: 'PRODUCT',
    scope: 'XLPE insulated, thermoplastic sheathed power cables for working voltages up to and including 1 100 V. Curated summary.',
    status: 'CURRENT',
    edition: 'Revision (2025)',
    publicationYear: 2025,
    keywords: ['xlpe', 'xlpe cable', 'power cable', 'armoured cable', '1.1 kv', '1100 v', 'lt cable', 'underground cable'],
    productTypes: ['power-cable'],
    versionHistory: [
      { designation: 'IS 7098 (Part 1) : 1988', year: 1988, label: 'Earlier edition (still referenced in the Cables QCO list)', status: 'SUPERSEDED' },
      { designation: 'IS 7098 (Part 1) : 2025', year: 2025, label: 'Current edition', status: 'CURRENT' },
    ],
    source: bisPortal('IS 7098'),
  }),
  std({
    id: 'is-10810-0',
    standardNumber: 'IS 10810 (Part 0)',
    baseNumber: '10810',
    part: '0',
    prefix: 'IS',
    title: 'Methods of Test for Cables — Part 0: General',
    sector: 'ELECTRICAL',
    kind: 'TEST_METHOD',
    scope: 'General part of the IS 10810 series of methods of test for electric cables; individual tests are specified in further parts. Curated summary; reaffirmed 2021.',
    status: 'CURRENT',
    publicationYear: 1984,
    keywords: ['cable test', 'methods of test', 'conductor resistance', 'insulation resistance', 'test method'],
    source: bisPortal('IS 10810'),
  }),

  // ------------------------------------------------------- Transformers
  std({
    id: 'is-1180-1',
    standardNumber: 'IS 1180 (Part 1)',
    baseNumber: '1180',
    part: '1',
    prefix: 'IS',
    title: 'Outdoor Type Oil Immersed Distribution Transformers up to and including 2 500 kVA, 33 kV — Specification — Part 1: Mineral Oil Immersed',
    sector: 'ELECTRICAL',
    kind: 'PRODUCT',
    scope: 'Outdoor type, mineral oil immersed distribution transformers up to and including 2 500 kVA and 33 kV, including energy efficiency levels. Curated summary; reaffirmed 2019; amalgamated the former Part 2.',
    status: 'CURRENT',
    edition: 'Fourth Revision',
    publicationYear: 2014,
    keywords: ['distribution transformer', 'oil immersed', 'kva', 'outdoor transformer', 'energy efficiency level', 'star rating', '11 kv'],
    productTypes: ['distribution-transformer'],
    source: bisPortal('IS 1180'),
  }),
  std({
    id: 'is-2026-1',
    standardNumber: 'IS 2026 (Part 1)',
    baseNumber: '2026',
    part: '1',
    prefix: 'IS',
    title: 'Power Transformers — Part 1: General',
    sector: 'ELECTRICAL',
    kind: 'PRODUCT',
    scope: 'General requirements for power transformers, including ratings, tolerances and tests. Curated summary; reaffirmed 2021; IEC basis not verified.',
    status: 'CURRENT',
    publicationYear: 2011,
    keywords: ['power transformer', 'transformer', 'rating', 'temperature rise'],
    productTypes: [],
    source: bisPortal('IS 2026'),
  }),
  std({
    id: 'is-335',
    standardNumber: 'IS 335',
    baseNumber: '335',
    prefix: 'IS',
    title: 'New Insulating Oils — Specification',
    sector: 'ELECTRICAL',
    kind: 'PRODUCT',
    scope: 'Unused mineral insulating oils for transformers and switchgear. Curated summary; largely based on IEC 60296 : 2012.',
    status: 'CURRENT',
    edition: 'Fifth Revision',
    publicationYear: 2018,
    keywords: ['insulating oil', 'transformer oil', 'mineral oil'],
    productTypes: [],
    source: bisPortal('IS 335'),
  }),

  // ------------------------------------------------------- Batteries & solar
  std({
    id: 'is-16046-2',
    standardNumber: 'IS 16046 (Part 2)',
    baseNumber: '16046',
    part: '2',
    prefix: 'IS',
    title: 'Secondary Cells and Batteries Containing Alkaline or Other Non-Acid Electrolytes — Safety Requirements for Portable Sealed Secondary Cells and for Batteries Made from Them — Part 2: Lithium Systems',
    sector: 'ELECTRONICS_IT',
    kind: 'SAFETY',
    scope: 'Safety requirements for portable sealed secondary lithium cells and batteries. Curated summary; corresponds to IEC 62133-2 : 2017.',
    status: 'CURRENT',
    edition: 'Second Revision',
    publicationYear: 2018,
    adoptedFrom: 'IEC 62133-2:2017',
    keywords: ['lithium ion', 'li-ion', 'battery', 'secondary cell', 'battery pack', 'lithium battery'],
    productTypes: ['li-ion-battery'],
    source: bisPortal('IS 16046'),
  }),
  std({
    id: 'is-14286-1',
    standardNumber: 'IS 14286 (Part 1)',
    baseNumber: '14286',
    part: '1',
    prefix: 'IS',
    title: 'Terrestrial Photovoltaic (PV) Modules — Design Qualification and Type Approval — Part 1: Test Requirements',
    sector: 'RENEWABLE_ENERGY',
    kind: 'PRODUCT',
    scope: 'Design qualification and type approval test requirements for terrestrial photovoltaic modules. Curated summary; corresponds to IEC 61215-1 : 2021. The earlier IS 14286 : 2010 (IEC 61215 : 2005) is also listed as active.',
    status: 'CURRENT',
    publicationYear: 2023,
    adoptedFrom: 'IEC 61215-1:2021',
    keywords: ['solar pv module', 'photovoltaic', 'solar panel', 'design qualification', 'type approval', 'crystalline silicon'],
    productTypes: ['solar-pv-module'],
    source: bisPortal('IS 14286'),
  }),
  std({
    id: 'is-14286-2',
    standardNumber: 'IS 14286 (Part 2)',
    baseNumber: '14286',
    part: '2',
    prefix: 'IS',
    title: 'Terrestrial Photovoltaic (PV) Modules — Design Qualification and Type Approval — Part 2: Test Procedures',
    sector: 'RENEWABLE_ENERGY',
    kind: 'TEST_METHOD',
    scope: 'Test procedures for design qualification and type approval of terrestrial PV modules. Curated summary.',
    status: 'CURRENT',
    publicationYear: 2023,
    keywords: ['pv module test', 'test procedure', 'photovoltaic'],
    source: bisPortal('IS 14286'),
  }),
  std({
    id: 'is-iec-61730-1',
    standardNumber: 'IS/IEC 61730 (Part 1)',
    baseNumber: '61730',
    part: '1',
    prefix: 'IS/IEC',
    title: 'Photovoltaic (PV) Module Safety Qualification — Part 1: Requirements for Construction',
    sector: 'RENEWABLE_ENERGY',
    kind: 'SAFETY',
    scope: 'Construction requirements for the safety qualification of PV modules. Curated summary; corresponds to IEC 61730-1 : 2023; replaces the 2004 edition.',
    status: 'CURRENT',
    publicationYear: 2023,
    adoptedFrom: 'IEC 61730-1:2023',
    keywords: ['pv module safety', 'photovoltaic', 'safety qualification', 'solar module'],
    productTypes: ['solar-pv-module'],
    source: bisPortal('IS/IEC 61730'),
  }),
  std({
    id: 'is-iec-61730-2',
    standardNumber: 'IS/IEC 61730 (Part 2)',
    baseNumber: '61730',
    part: '2',
    prefix: 'IS/IEC',
    title: 'Photovoltaic (PV) Module Safety Qualification — Part 2: Requirements for Testing',
    sector: 'RENEWABLE_ENERGY',
    kind: 'TEST_METHOD',
    scope: 'Testing requirements for the safety qualification of PV modules. Curated summary; corresponds to IEC 61730-2 : 2023.',
    status: 'CURRENT',
    publicationYear: 2023,
    adoptedFrom: 'IEC 61730-2:2023',
    keywords: ['pv module safety test', 'photovoltaic', 'safety testing'],
    source: bisPortal('IS/IEC 61730'),
  }),

  // ------------------------------------------------------- Construction
  std({
    id: 'is-269',
    standardNumber: 'IS 269',
    baseNumber: '269',
    prefix: 'IS',
    title: 'Ordinary Portland Cement — Specification',
    sector: 'CIVIL_CONSTRUCTION',
    kind: 'PRODUCT',
    scope: 'Ordinary Portland cement of 33, 43 and 53 grades (including the former separate 43 and 53 grade standards), with chemical and physical requirements. Curated summary; reaffirmed 2020.',
    status: 'CURRENT',
    edition: 'Sixth Revision',
    publicationYear: 2015,
    keywords: ['ordinary portland cement', 'opc', 'cement', '43 grade', '53 grade', '33 grade', 'compressive strength', 'setting time', 'fineness'],
    productTypes: ['portland-cement'],
    supersedes: [
      { standardId: 'is-8112', designation: 'IS 8112 : 2013', note: 'BIS portal lists IS 8112 : 2013 as superseded by IS 269 : 2015.' },
      { standardId: 'is-12269', designation: 'IS 12269 : 2013', note: 'BIS portal lists IS 12269 : 2013 as superseded by IS 269 : 2015.' },
    ],
    versionHistory: [
      { designation: 'IS 269 : 2015', year: 2015, label: 'Sixth Revision (merged 33, 43 and 53 grades)', status: 'CURRENT' },
    ],
    amendmentDataStatus: 'INDEXED',
    amendments: [portalAmendment('IS 269 : 2015', 1)],
    source: bisPortal('IS 269', 'Listed with 1 amendment; reaffirmed 2020.'),
  }),
  std({
    id: 'is-8112',
    standardNumber: 'IS 8112',
    baseNumber: '8112',
    prefix: 'IS',
    title: 'Ordinary Portland Cement, 43 Grade — Specification',
    sector: 'CIVIL_CONSTRUCTION',
    kind: 'PRODUCT',
    scope: 'Former separate specification for 43 grade ordinary Portland cement. Recorded as withdrawn and superseded by IS 269 : 2015.',
    status: 'SUPERSEDED',
    publicationYear: 2013,
    supersededBy: { standardId: 'is-269', designation: 'IS 269 : 2015' },
    versionHistory: [{ designation: 'IS 8112 : 2013', year: 2013, label: 'Last edition before merger into IS 269', status: 'SUPERSEDED' }],
    keywords: ['43 grade', 'opc', 'cement'],
    productTypes: ['portland-cement'],
    verification: TITLE_NOTE,
    source: bisPortal('IS 8112', 'Portal: "Superseded by IS 269 : 2015".'),
  }),
  std({
    id: 'is-12269',
    standardNumber: 'IS 12269',
    baseNumber: '12269',
    prefix: 'IS',
    title: 'Ordinary Portland Cement, 53 Grade — Specification',
    sector: 'CIVIL_CONSTRUCTION',
    kind: 'PRODUCT',
    scope: 'Former separate specification for 53 grade ordinary Portland cement. Recorded as withdrawn and superseded by IS 269 : 2015.',
    status: 'SUPERSEDED',
    publicationYear: 2013,
    supersededBy: { standardId: 'is-269', designation: 'IS 269 : 2015' },
    keywords: ['53 grade', 'opc', 'cement'],
    productTypes: ['portland-cement'],
    verification: TITLE_NOTE,
    source: bisPortal('IS 12269', 'Portal: "Superseded by IS 269 : 2015".'),
  }),
  std({
    id: 'is-1489-1',
    standardNumber: 'IS 1489 (Part 1)',
    baseNumber: '1489',
    part: '1',
    prefix: 'IS',
    title: 'Portland Pozzolana Cement — Specification — Part 1: Fly Ash Based',
    sector: 'CIVIL_CONSTRUCTION',
    kind: 'PRODUCT',
    scope: 'Fly ash based Portland pozzolana cement, with chemical and physical requirements. Curated summary; reaffirmed 2020.',
    status: 'CURRENT',
    edition: 'Fourth Revision',
    publicationYear: 2015,
    keywords: ['portland pozzolana cement', 'ppc', 'fly ash', 'cement', 'pozzolana'],
    productTypes: ['ppc-cement'],
    versionHistory: [
      { designation: 'IS 1489 (Part 1) : 1991', year: 1991, label: 'Third Revision', status: 'SUPERSEDED' },
      { designation: 'IS 1489 (Part 1) : 2015', year: 2015, label: 'Fourth Revision', status: 'CURRENT' },
    ],
    source: bisPortal('IS 1489'),
  }),
  std({
    id: 'is-4031',
    standardNumber: 'IS 4031 (series)',
    baseNumber: '4031',
    prefix: 'IS',
    title: 'Methods of Physical Tests for Hydraulic Cement (Parts 1 to 15)',
    sector: 'CIVIL_CONSTRUCTION',
    kind: 'TEST_METHOD',
    scope: 'Series of methods of physical tests for hydraulic cement, including fineness, soundness, consistency, setting times and compressive strength. Individual parts have different editions (Part 1 : 1996, Part 2 : 1999, Parts 3–13 : 1988, Part 14 : 1989, Part 15 : 1991), all reaffirmed between 2018 and 2021. Curated summary.',
    status: 'CURRENT',
    keywords: ['physical tests', 'cement testing', 'compressive strength', 'setting time', 'fineness', 'soundness', 'test method'],
    source: bisPortal('IS 4031'),
  }),
  std({
    id: 'is-4032',
    standardNumber: 'IS 4032',
    baseNumber: '4032',
    prefix: 'IS',
    title: 'Method of Chemical Analysis of Hydraulic Cement',
    sector: 'CIVIL_CONSTRUCTION',
    kind: 'TEST_METHOD',
    scope: 'Methods of chemical analysis of hydraulic cement. Curated summary; reaffirmed 2019.',
    status: 'CURRENT',
    publicationYear: 1985,
    keywords: ['chemical analysis', 'cement testing', 'test method'],
    source: bisPortal('IS 4032'),
  }),
  std({
    id: 'is-456',
    standardNumber: 'IS 456',
    baseNumber: '456',
    prefix: 'IS',
    title: 'Plain and Reinforced Concrete — Code of Practice',
    sector: 'CIVIL_CONSTRUCTION',
    kind: 'CODE_OF_PRACTICE',
    scope: 'Code of practice for the use of plain and reinforced concrete in general building construction, covering materials, durability, workmanship, design and acceptance criteria. Curated summary; reaffirmed 2021.',
    status: 'CURRENT',
    edition: 'Fourth Revision',
    publicationYear: 2000,
    keywords: ['reinforced concrete', 'plain concrete', 'rcc', 'concrete mix', 'durability', 'concrete grade', 'code of practice'],
    productTypes: ['concrete-works'],
    source: bisPortal('IS 456'),
  }),
  std({
    id: 'is-383',
    standardNumber: 'IS 383',
    baseNumber: '383',
    prefix: 'IS',
    title: 'Coarse and Fine Aggregate for Concrete — Specification',
    sector: 'CIVIL_CONSTRUCTION',
    kind: 'PRODUCT',
    scope: 'Requirements for coarse and fine aggregates from natural and other sources for use in concrete. Curated summary.',
    status: 'CURRENT',
    edition: 'Third Revision',
    publicationYear: 2016,
    keywords: ['coarse aggregate', 'fine aggregate', 'sand', 'aggregate', 'crushed stone', 'grading'],
    productTypes: ['aggregates'],
    source: bisPortal('IS 383'),
  }),
  std({
    id: 'is-1786',
    standardNumber: 'IS 1786',
    baseNumber: '1786',
    prefix: 'IS',
    title: 'High Strength Deformed Steel Bars and Wires for Concrete Reinforcement — Specification',
    sector: 'CIVIL_CONSTRUCTION',
    kind: 'PRODUCT',
    scope: 'High strength deformed steel bars and wires for concrete reinforcement, in grades such as Fe 415, Fe 500, Fe 550 and Fe 600 and their D/S variants. Curated summary; reaffirmed 2018.',
    status: 'CURRENT',
    edition: 'Fourth Revision',
    publicationYear: 2008,
    keywords: ['tmt', 'deformed bars', 'reinforcement', 'rebar', 'fe 500', 'fe 500d', 'steel bars', 'hysd'],
    productTypes: ['tmt-bars'],
    source: bisPortal('IS 1786'),
  }),
  std({
    id: 'is-1608-1',
    standardNumber: 'IS 1608 (Part 1)',
    baseNumber: '1608',
    part: '1',
    prefix: 'IS',
    title: 'Metallic Materials — Tensile Testing — Part 1: Method of Test at Room Temperature',
    sector: 'CIVIL_CONSTRUCTION',
    kind: 'TEST_METHOD',
    scope: 'Method of tensile testing of metallic materials at room temperature. Curated summary; corresponds to ISO 6892-1 : 2019. IS 1608 : 2005 is recorded as withdrawn, superseded by Parts 1 and 3.',
    status: 'CURRENT',
    publicationYear: 2022,
    adoptedFrom: 'ISO 6892-1:2019',
    keywords: ['tensile test', 'metallic materials', 'yield strength', 'elongation', 'test method'],
    source: bisPortal('IS 1608'),
  }),
  std({
    id: 'is-2062',
    standardNumber: 'IS 2062',
    baseNumber: '2062',
    prefix: 'IS',
    title: 'Hot Rolled Medium and High Tensile Structural Steel — Specification',
    sector: 'CIVIL_CONSTRUCTION',
    kind: 'PRODUCT',
    scope: 'Hot rolled medium and high tensile structural steel plates, sections and strips. Curated summary; the 2011 (Seventh Revision) edition is active. A new IS 2062 (Part 1) : 2025 is also listed; its relation to the 2011 edition is not verified.',
    status: 'CURRENT',
    edition: 'Seventh Revision',
    publicationYear: 2011,
    keywords: ['structural steel', 'hot rolled', 'steel plate', 'steel sections', 'e250', 'e350'],
    productTypes: ['structural-steel'],
    source: bisPortal('IS 2062'),
  }),

  // ------------------------------------------------------- Motors & pumps
  std({
    id: 'is-12615',
    standardNumber: 'IS 12615',
    baseNumber: '12615',
    prefix: 'IS',
    title: 'Line Operated Three Phase a.c. Motors (IE Code) — Efficiency Classes and Performance — Specification',
    sector: 'ELECTRICAL',
    kind: 'PRODUCT',
    scope: 'Efficiency classes (IE code) and performance requirements for line operated three-phase a.c. induction motors. Curated summary; the 2018 edition was based on IEC 60034-30-1 : 2014.',
    status: 'CURRENT',
    edition: 'Revision (2026)',
    publicationYear: 2026,
    keywords: ['induction motor', 'three phase motor', 'ie code', 'ie2', 'ie3', 'ie4', 'efficiency class', 'squirrel cage', 'energy efficient motor'],
    productTypes: ['induction-motor'],
    supersedes: [{ standardId: 'is-325', designation: 'IS 325 : 1996', note: 'BIS portal lists IS 325 : 1996 as withdrawn and superseded by IS 12615 : 2011.' }],
    versionHistory: [
      { designation: 'IS 12615 : 2011', year: 2011, label: 'Earlier edition (superseded IS 325)', status: 'SUPERSEDED' },
      { designation: 'IS 12615 : 2018', year: 2018, label: 'Third Revision (based on IEC 60034-30-1 : 2014)', status: 'SUPERSEDED' },
      { designation: 'IS 12615 : 2026', year: 2026, label: 'Current edition', status: 'CURRENT' },
    ],
    source: bisPortal('IS 12615'),
  }),
  std({
    id: 'is-325',
    standardNumber: 'IS 325',
    baseNumber: '325',
    prefix: 'IS',
    title: 'Three-phase Induction Motors',
    sector: 'ELECTRICAL',
    kind: 'PRODUCT',
    scope: 'Former general specification for three-phase induction motors. Recorded as withdrawn and superseded by IS 12615.',
    status: 'WITHDRAWN',
    publicationYear: 1996,
    supersededBy: { standardId: 'is-12615', designation: 'IS 12615' },
    keywords: ['induction motor', 'three phase motor'],
    productTypes: ['induction-motor'],
    source: bisPortal('IS 325', 'Withdrawn; superseded by IS 12615 : 2011.'),
  }),
  std({
    id: 'is-iec-60034-1',
    standardNumber: 'IS/IEC 60034-1',
    baseNumber: '60034',
    part: '1',
    prefix: 'IS/IEC',
    title: 'Rotating Electrical Machines — Part 1: Rating and Performance',
    sector: 'ELECTRICAL',
    kind: 'PRODUCT',
    scope: 'Rating and performance requirements applicable to rotating electrical machines, including duty types, temperature limits and tolerances. Curated summary; corresponds to IEC 60034-1 : 2022.',
    status: 'CURRENT',
    publicationYear: 2022,
    adoptedFrom: 'IEC 60034-1:2022',
    keywords: ['rotating machines', 'rating', 'duty type', 'temperature rise', 'motor performance'],
    productTypes: [],
    versionHistory: [
      { designation: 'IS/IEC 60034-1 : 2004', year: 2004, label: 'Earlier edition (identical with IEC 60034-1 : 2004)', status: 'SUPERSEDED' },
      { designation: 'IS/IEC 60034-1 : 2022', year: 2022, label: 'Current edition', status: 'CURRENT' },
    ],
    source: bisPortal('IS/IEC 60034'),
  }),
  std({
    id: 'is-15999-2-1',
    standardNumber: 'IS 15999 (Part 2/Sec 1)',
    baseNumber: '15999',
    part: '2',
    section: '1',
    prefix: 'IS',
    title: 'Rotating Electrical Machines — Part 2: Determining Losses and Efficiency from Tests — Section 1: Standard Methods (Excluding Machines for Traction Vehicles)',
    sector: 'ELECTRICAL',
    kind: 'TEST_METHOD',
    scope: 'Standard test methods for determining losses and efficiency of rotating electrical machines. Curated summary; corresponds to IEC 60034-2-1 : 2014; replaces the 2011 edition.',
    status: 'CURRENT',
    publicationYear: 2023,
    adoptedFrom: 'IEC 60034-2-1:2014',
    keywords: ['efficiency test', 'losses', 'motor testing', 'test method'],
    source: bisPortal('IS 15999'),
  }),
  std({
    id: 'is-9079',
    standardNumber: 'IS 9079',
    baseNumber: '9079',
    prefix: 'IS',
    title: 'Monoset Pumps for Clear, Cold Water for Agricultural and Water Supply Purposes — Specification',
    sector: 'MECHANICAL',
    kind: 'PRODUCT',
    scope: 'Electric monoset pumps for clear, cold water for agricultural and water supply purposes. Curated summary; reaffirmed 2022.',
    status: 'CURRENT',
    edition: 'Third Revision',
    publicationYear: 2018,
    keywords: ['monoset pump', 'monoblock pump', 'agricultural pump', 'water supply', 'clear cold water', 'pump'],
    productTypes: ['monoset-pump'],
    source: bisPortal('IS 9079'),
  }),
  std({
    id: 'is-8034',
    standardNumber: 'IS 8034',
    baseNumber: '8034',
    prefix: 'IS',
    title: 'Submersible Pumpsets — Specification',
    sector: 'MECHANICAL',
    kind: 'PRODUCT',
    scope: 'Submersible pumpsets for clear, cold water, typically for borewells in agricultural and water supply applications. Curated summary; reaffirmed 2022.',
    status: 'CURRENT',
    edition: 'Third Revision',
    publicationYear: 2018,
    keywords: ['submersible pump', 'submersible pumpset', 'borewell', 'agricultural pump', 'irrigation', 'water supply', 'pump'],
    productTypes: ['submersible-pumpset'],
    amendmentDataStatus: 'INDEXED',
    amendments: [portalAmendment('IS 8034 : 2018', 1), portalAmendment('IS 8034 : 2018', 2), portalAmendment('IS 8034 : 2018', 3)],
    versionHistory: [
      { designation: 'IS 8034 : 2002', year: 2002, label: 'Second Revision', status: 'SUPERSEDED' },
      { designation: 'IS 8034 : 2018', year: 2018, label: 'Third Revision', status: 'CURRENT' },
    ],
    source: bisPortal('IS 8034', 'Listed with 3 amendments; reaffirmed 2022.'),
  }),
  std({
    id: 'is-14220',
    standardNumber: 'IS 14220',
    baseNumber: '14220',
    prefix: 'IS',
    title: 'Openwell Submersible Pumpsets — Specification',
    sector: 'MECHANICAL',
    kind: 'PRODUCT',
    scope: 'Openwell submersible pumpsets for clear, cold water. Curated summary; reaffirmed 2022.',
    status: 'CURRENT',
    edition: 'First Revision',
    publicationYear: 2018,
    keywords: ['openwell submersible', 'open well pump', 'submersible pumpset', 'pump'],
    productTypes: ['openwell-submersible'],
    source: bisPortal('IS 14220'),
  }),
  std({
    id: 'is-6595-1',
    standardNumber: 'IS 6595 (Part 1)',
    baseNumber: '6595',
    part: '1',
    prefix: 'IS',
    title: 'Horizontal Centrifugal Pumps for Clear, Cold Water — Specification — Part 1: Agricultural and Rural Water Supply Purposes',
    sector: 'MECHANICAL',
    kind: 'PRODUCT',
    scope: 'Horizontal centrifugal pumps for clear, cold water for agricultural and rural water supply purposes. Curated summary; reaffirmed 2022; Part 2 : 2024 also exists.',
    status: 'CURRENT',
    edition: 'Fourth Revision',
    publicationYear: 2018,
    keywords: ['centrifugal pump', 'horizontal pump', 'agricultural pump', 'rural water supply', 'pump'],
    productTypes: ['centrifugal-pump'],
    source: bisPortal('IS 6595'),
  }),
  std({
    id: 'is-11346',
    standardNumber: 'IS 11346',
    baseNumber: '11346',
    prefix: 'IS',
    title: 'Tests for Agricultural and Water Supply Pumps — Code of Acceptance',
    sector: 'MECHANICAL',
    kind: 'TEST_METHOD',
    scope: 'Code of acceptance tests for agricultural and water supply pumps, covering measurement of flow, head, power input and efficiency. Curated summary; reaffirmed 2017.',
    status: 'CURRENT',
    edition: 'First Revision',
    publicationYear: 2002,
    keywords: ['pump test', 'acceptance test', 'head', 'discharge', 'pump efficiency', 'test method'],
    source: bisPortal('IS 11346'),
  }),
  std({
    id: 'is-9283',
    standardNumber: 'IS 9283',
    baseNumber: '9283',
    prefix: 'IS',
    title: 'Line Operated a.c. Motors for Submersible Pumpsets — Specification',
    sector: 'ELECTRICAL',
    kind: 'COMPONENT',
    scope: 'Line operated a.c. motors for submersible pumpsets. Curated summary; replaces IS 9283 : 2013.',
    status: 'CURRENT',
    edition: 'Third Revision',
    publicationYear: 2024,
    keywords: ['submersible motor', 'pump motor', 'water filled motor', 'oil filled motor'],
    productTypes: [],
    versionHistory: [
      { designation: 'IS 9283 : 2013', year: 2013, label: 'Earlier edition', status: 'SUPERSEDED' },
      { designation: 'IS 9283 : 2024', year: 2024, label: 'Third Revision', status: 'CURRENT' },
    ],
    source: bisPortal('IS 9283'),
  }),
];
