/**
 * Product taxonomy and parameter templates (curated benchmark data).
 * Aliases are technical names and trade synonyms used to recognise products;
 * they are not translations. Templates list parameters a procurement
 * specification is expected to state, each with its rationale.
 */
import type { ParameterRequirement, ProductCategory } from '../../../shared/knowledge';

type Req = Omit<ParameterRequirement, 'criticalWhenOutdoor' | 'termsAny' | 'relatedStandardIds' | 'quantityKinds'> &
  Partial<Pick<ParameterRequirement, 'criticalWhenOutdoor' | 'termsAny' | 'relatedStandardIds' | 'quantityKinds'>>;
const req = (r: Req): ParameterRequirement => ({ criticalWhenOutdoor: false, termsAny: [], relatedStandardIds: [], quantityKinds: [], ...r });

const quantity = req({
  key: 'quantity',
  label: 'Quantity',
  quantityKinds: ['QUANTITY'],
  termsAny: ['quantity', 'qty'],
  severity: 'INFO',
  whyItMatters: 'Quantity drives price, delivery schedule and inspection sampling.',
  suggestion: 'State the number of units (or total mass/length) to be supplied.',
});

const warranty = req({
  key: 'warranty',
  label: 'Warranty period',
  quantityKinds: ['DURATION'],
  termsAny: ['warranty', 'guarantee'],
  severity: 'INFO',
  whyItMatters: 'Warranty terms set the supplier’s obligations after acceptance.',
  suggestion: 'State the warranty period and what it covers (e.g. 3 years comprehensive).',
});

const ambient = req({
  key: 'operating_temperature',
  label: 'Operating ambient temperature range',
  quantityKinds: ['TEMPERATURE'],
  termsAny: ['ambient temperature', 'operating temperature'],
  severity: 'WARNING',
  whyItMatters: 'Indian site conditions frequently exceed default ambient assumptions; ratings depend on ambient temperature.',
  suggestion: 'State the ambient temperature range (e.g. −5 °C to +50 °C).',
});

function evCommon(): ParameterRequirement[] {
  return [
    req({
      key: 'ip_rating',
      label: 'Enclosure ingress protection (IP rating)',
      quantityKinds: ['IP_RATING'],
      severity: 'WARNING',
      criticalWhenOutdoor: true,
      whyItMatters: 'Outdoor chargers are exposed to dust and rain; the IP code determines whether the enclosure is suitable for the site.',
      suggestion: 'Specify the minimum IP rating of the charger enclosure (e.g. IP54 or IP55) as per IS/IEC 60529.',
      relatedStandardIds: ['is-iec-60529'],
    }),
    req({
      key: 'ik_rating',
      label: 'Mechanical impact protection (IK rating)',
      quantityKinds: ['IK_RATING'],
      severity: 'INFO',
      whyItMatters: 'Publicly accessible equipment is exposed to impact and vandalism.',
      suggestion: 'Specify the minimum IK rating for public installations (e.g. IK08 or IK10).',
    }),
    ambient,
    req({
      key: 'protection',
      label: 'Electrical protection devices',
      quantityKinds: ['PROTECTION_DEVICE'],
      termsAny: ['residual current', 'earth leakage', 'overcurrent'],
      severity: 'CRITICAL',
      whyItMatters: 'Residual current and overcurrent protection are fundamental to user safety at a charging point.',
      suggestion: 'Specify residual current protection (type to be confirmed against IS 17017 (Part 1)) and overcurrent protection of the dedicated circuit.',
      relatedStandardIds: ['is-12640-1', 'is-iec-60898-1'],
    }),
    req({
      key: 'communication',
      label: 'Communication and back-end management',
      quantityKinds: ['COMMUNICATION_PROTOCOL'],
      termsAny: ['ocpp', 'communication protocol', 'central management system', 'cms'],
      severity: 'WARNING',
      whyItMatters: 'Remote monitoring, billing and interoperability depend on the communication protocols supported.',
      suggestion: 'Specify back-end communication (e.g. OCPP version) and whether vehicle communication per IS/ISO 15118 is required.',
      relatedStandardIds: ['is-iso-15118-2'],
    }),
    req({
      key: 'metering',
      label: 'Energy metering',
      termsAny: ['energy meter', 'metering', 'kwh meter', 'billing'],
      severity: 'WARNING',
      whyItMatters: 'Public charging requires measured energy for billing and reporting.',
      suggestion: 'Specify an energy meter for each output and its accuracy class.',
    }),
    req({
      key: 'user_authentication',
      label: 'User authentication and payment',
      termsAny: ['rfid', 'authentication', 'payment', 'mobile app', 'qr code'],
      severity: 'INFO',
      whyItMatters: 'Public chargers need a defined way to start sessions and collect payment.',
      suggestion: 'Specify supported authentication/payment methods (e.g. RFID, app, QR/UPI).',
    }),
    quantity,
    warranty,
  ];
}

const EV_TEMPLATE_SOURCE =
  'Template curated by FiiSpec from the parameters addressed by the IS 17017 series and the MoP Guidelines for EV Charging Infrastructure (2024). Benchmark data — not an official checklist.';

export const CATEGORIES: ProductCategory[] = [
  {
    id: 'ev-charging-equipment',
    label: 'EV charging equipment',
    sector: 'ELECTROTECHNICAL_EV',
    aliases: ['ev charger', 'ev chargers', 'electric vehicle charger', 'evse', 'ev supply equipment', 'electric vehicle supply equipment', 'charging station', 'ev charging station', 'charging point', 'charge point', 'ev charging', 'charging infrastructure', 'e-vehicle charger'],
    description: 'Equipment that supplies energy to electric vehicles by conductive charging (AC or DC).',
    requiresInstallation: true,
    parameterTemplate: [
      req({
        key: 'charger_type',
        label: 'Charger type (AC or DC)',
        termsAny: ['ac charger', 'dc charger', 'a.c.', 'd.c.', 'ac charging', 'dc charging', 'alternating current', 'direct current'],
        severity: 'CRITICAL',
        whyItMatters: 'AC and DC chargers are covered by different parts of IS 17017 and have very different supply and cost implications.',
        suggestion: 'State whether AC or DC charging equipment is required.',
      }),
      req({
        key: 'rated_power',
        label: 'Rated output power',
        quantityKinds: ['POWER'],
        severity: 'CRITICAL',
        whyItMatters: 'Rated power determines the charger configuration, supply capacity and cabling.',
        suggestion: 'State rated output power per connector in kW.',
      }),
      req({
        key: 'connector_type',
        label: 'Vehicle connector type',
        quantityKinds: ['CONNECTOR'],
        severity: 'CRITICAL',
        whyItMatters: 'The connector must match the vehicles to be charged.',
        suggestion: 'Specify the connector type and the applicable part of IS 17017 (Part 2).',
        relatedStandardIds: ['is-17017-2-2', 'is-17017-2-3'],
      }),
      ...evCommon(),
    ],
    templateSource: EV_TEMPLATE_SOURCE,
    lifecycle: 'PUBLISHED',
  },
  {
    id: 'ev-ac-charger',
    label: 'AC EV charging station',
    sector: 'ELECTROTECHNICAL_EV',
    parentId: 'ev-charging-equipment',
    aliases: ['ac charger', 'ac ev charger', 'ac charging station', 'ac charge point', 'ac evse', 'wallbox', 'wall box', 'wall-mounted charger', 'type 2 charger', 'parkbay charger', 'destination charger', 'level 2 charger', 'ac charging', 'mode 3 charger', '7.4 kw charger', '11 kw charger', '22 kw charger'],
    description: 'AC charging station (Mode 3) supplying the vehicle on-board charger, typically 7.4–22 kW for parking bays.',
    requiresInstallation: true,
    parameterTemplate: [
      req({
        key: 'rated_power',
        label: 'Rated output power',
        quantityKinds: ['POWER'],
        severity: 'CRITICAL',
        whyItMatters: 'AC charging power (e.g. 7.4, 11 or 22 kW) determines the supply connection, cabling and protection rating.',
        suggestion: 'State rated output power per connector in kW.',
      }),
      req({
        key: 'supply_voltage',
        label: 'Supply voltage and phases',
        quantityKinds: ['VOLTAGE', 'PHASE'],
        severity: 'CRITICAL',
        whyItMatters: '11 kW and 22 kW AC charging require a three-phase supply; the supply must be defined for installation and protection design.',
        suggestion: 'State input supply voltage, number of phases and frequency (e.g. 415 V, three-phase, 50 Hz).',
      }),
      req({
        key: 'output_current',
        label: 'Rated output current',
        quantityKinds: ['CURRENT'],
        severity: 'WARNING',
        whyItMatters: 'Rated current sizes the connector, cable and protective devices.',
        suggestion: 'State rated output current per phase (e.g. 16 A or 32 A).',
      }),
      req({
        key: 'connector_type',
        label: 'Vehicle connector type',
        quantityKinds: ['CONNECTOR'],
        severity: 'CRITICAL',
        whyItMatters: 'The MoP 2024 guidelines map AC parkbay charging to IS 17017 (Part 2/Sec 2) accessories; the connector must match the vehicles.',
        suggestion: 'Specify the connector (e.g. Type 2 socket or tethered connector) as per IS 17017 (Part 2/Sec 2).',
        relatedStandardIds: ['is-17017-2-2'],
      }),
      req({
        key: 'charging_mode',
        label: 'Charging mode',
        quantityKinds: ['CHARGING_MODE'],
        severity: 'INFO',
        whyItMatters: 'The charging mode defines the control and protection functions required.',
        suggestion: 'State the charging mode (Mode 3 for AC charging stations) as per IS 17017 (Part 1).',
        relatedStandardIds: ['is-17017-1'],
      }),
      req({
        key: 'number_of_outputs',
        label: 'Number of charging outputs',
        termsAny: ['outputs', 'output points', 'dual output', 'single output', 'connectors per charger', 'number of connectors', 'twin'],
        severity: 'INFO',
        whyItMatters: 'The number of simultaneous outputs changes supply sizing and price.',
        suggestion: 'State the number of charging outputs per charger and whether they operate simultaneously.',
      }),
      ...evCommon(),
    ],
    templateSource: EV_TEMPLATE_SOURCE,
    lifecycle: 'PUBLISHED',
  },
  {
    id: 'ev-dc-charger',
    label: 'DC fast charger',
    sector: 'ELECTROTECHNICAL_EV',
    parentId: 'ev-charging-equipment',
    aliases: ['dc charger', 'dc fast charger', 'fast charger', 'dc evse', 'rapid charger', 'ccs2 charger', 'dc charging station', 'dual gun charger', 'high power charger', 'dcfc'],
    description: 'DC electric vehicle supply equipment converting AC supply to DC for direct battery charging, typically 30–500 kW.',
    requiresInstallation: true,
    parameterTemplate: [
      req({ key: 'rated_power', label: 'Rated output power', quantityKinds: ['POWER'], severity: 'CRITICAL', whyItMatters: 'DC charger power (e.g. 60 kW, 120 kW) determines the supply connection and the MoP Annexure-I standards set.', suggestion: 'State rated DC output power and power sharing between guns, in kW.' }),
      req({ key: 'output_voltage_range', label: 'DC output voltage range', quantityKinds: ['VOLTAGE'], severity: 'CRITICAL', whyItMatters: 'The output voltage range must cover the battery voltages of the target vehicles.', suggestion: 'State the DC output voltage range (e.g. 200–1000 V DC).' }),
      req({ key: 'output_current', label: 'Maximum DC output current', quantityKinds: ['CURRENT'], severity: 'WARNING', whyItMatters: 'Maximum current limits the achievable power at lower battery voltages.', suggestion: 'State maximum output current per gun (A).' }),
      req({ key: 'connector_type', label: 'Vehicle connector type', quantityKinds: ['CONNECTOR'], severity: 'CRITICAL', whyItMatters: 'The MoP 2024 guidelines map DC charging to IS 17017 (Part 2/Sec 3) couplers; the connector must match the vehicles.', suggestion: 'Specify the DC coupler (e.g. CCS2) as per IS 17017 (Part 2/Sec 3).', relatedStandardIds: ['is-17017-2-3'] }),
      req({ key: 'efficiency', label: 'Efficiency and power factor', quantityKinds: ['EFFICIENCY', 'POWER_FACTOR'], severity: 'WARNING', whyItMatters: 'Conversion efficiency and power factor affect energy cost and grid compliance.', suggestion: 'Specify minimum efficiency at rated load and minimum input power factor.' }),
      req({ key: 'supply_voltage', label: 'AC input supply', quantityKinds: ['PHASE', 'FREQUENCY'], termsAny: ['input supply', 'input voltage'], severity: 'CRITICAL', whyItMatters: 'The AC input connection (LT/HT, phases) determines site electrical works.', suggestion: 'State the AC input voltage, phases and frequency.' }),
      ...evCommon(),
    ],
    templateSource: EV_TEMPLATE_SOURCE,
    lifecycle: 'PUBLISHED',
  },
  {
    id: 'ev-lev-charger',
    label: 'Light EV charge point',
    sector: 'ELECTROTECHNICAL_EV',
    parentId: 'ev-charging-equipment',
    aliases: ['light electric vehicle charger', 'lev charger', 'lev charge point', 'e-rickshaw charger', 'two wheeler charger', 'two-wheeler charger', 'three wheeler charger', 'three-wheeler charger', '2w charger', '3w charger', 'e-scooter charger', 'electric scooter charger'],
    description: 'Charge points for light electric vehicles (two- and three-wheelers), AC up to about 7 kW or LEV DC.',
    requiresInstallation: true,
    parameterTemplate: [
      req({ key: 'rated_power', label: 'Rated output power', quantityKinds: ['POWER'], severity: 'CRITICAL', whyItMatters: 'LEV charging covers AC charge points (IS 17017 (Part 22/Sec 1)) and LEV DC (IS 17017 (Part 25)); power decides which applies.', suggestion: 'State rated output power in kW and whether AC or DC output is required.' }),
      req({ key: 'socket_type', label: 'Socket / connector type', quantityKinds: ['CONNECTOR'], termsAny: ['socket', '60309'], severity: 'CRITICAL', whyItMatters: 'LEV AC charge points use IS/IEC 60309 industrial sockets per the MoP guidelines; LEV DC uses IS 17017 (Part 2/Sec 6) couplers.', suggestion: 'Specify the socket or coupler type.', relatedStandardIds: ['is-17017-2-6'] }),
      ...evCommon(),
    ],
    templateSource: EV_TEMPLATE_SOURCE,
    lifecycle: 'PUBLISHED',
  },
  {
    id: 'ev-connector',
    label: 'EV connector / charging cable',
    sector: 'ELECTROTECHNICAL_EV',
    parentId: 'ev-charging-equipment',
    aliases: ['vehicle connector', 'charging connector', 'type 2 connector', 'charging cable', 'vehicle inlet', 'ev plug', 'ccs2 connector', 'charging gun'],
    description: 'Plugs, socket-outlets, vehicle connectors, inlets and charging cable assemblies.',
    requiresInstallation: false,
    parameterTemplate: [
      req({ key: 'connector_type', label: 'Connector type', quantityKinds: ['CONNECTOR'], severity: 'CRITICAL', whyItMatters: 'Connector dimensions determine vehicle compatibility.', suggestion: 'Specify the connector family and the applicable IS 17017 (Part 2) section.' }),
      req({ key: 'rated_current', label: 'Rated current', quantityKinds: ['CURRENT'], severity: 'CRITICAL', whyItMatters: 'Rated current sizes contacts and cable.', suggestion: 'State the rated current (A).' }),
      req({ key: 'rated_voltage', label: 'Rated voltage', quantityKinds: ['VOLTAGE'], severity: 'WARNING', whyItMatters: 'Rated voltage must match the charging system.', suggestion: 'State the rated voltage.' }),
      quantity,
    ],
    templateSource: EV_TEMPLATE_SOURCE,
    lifecycle: 'PUBLISHED',
  },
  {
    id: 'induction-motor',
    label: 'Three-phase induction motor',
    sector: 'ELECTRICAL',
    aliases: ['induction motor', 'three phase motor', 'three-phase motor', '3 phase motor', 'squirrel cage motor', 'squirrel cage induction motor', 'ie2 motor', 'ie3 motor', 'ie4 motor', 'energy efficient motor', 'ac motor', 'electric motor', 'lt motor'],
    description: 'Line-operated three-phase squirrel-cage induction motors for industrial drives.',
    requiresInstallation: false,
    parameterTemplate: [
      req({ key: 'rated_power', label: 'Rated output power', quantityKinds: ['POWER'], severity: 'CRITICAL', whyItMatters: 'Rated power defines the motor frame and the applicable IE efficiency values.', suggestion: 'State rated output in kW.' }),
      req({ key: 'supply', label: 'Supply voltage and frequency', quantityKinds: ['VOLTAGE', 'FREQUENCY'], severity: 'CRITICAL', whyItMatters: 'Motor windings are designed for a specific supply.', suggestion: 'State rated voltage, frequency and permissible variations (e.g. 415 V ±10 %, 50 Hz ±5 %).' }),
      req({ key: 'efficiency_class', label: 'Efficiency class (IE code)', quantityKinds: ['EFFICIENCY_CLASS'], severity: 'CRITICAL', whyItMatters: 'IS 12615 defines IE efficiency classes; the class drives lifetime energy cost and may be subject to a Quality Control Order.', suggestion: 'Specify the minimum efficiency class (e.g. IE3) as per IS 12615.', relatedStandardIds: ['is-12615'] }),
      req({ key: 'speed', label: 'Synchronous speed / number of poles', quantityKinds: ['SPEED'], termsAny: ['pole', 'poles'], severity: 'WARNING', whyItMatters: 'Speed must match the driven equipment.', suggestion: 'State synchronous speed or pole number (e.g. 1500 rpm, 4-pole).' }),
      req({ key: 'duty', label: 'Duty type', termsAny: ['s1', 'duty', 'continuous duty'], severity: 'WARNING', whyItMatters: 'Duty type affects thermal rating (IS/IEC 60034-1).', suggestion: 'State the duty type (e.g. S1 continuous).', relatedStandardIds: ['is-iec-60034-1'] }),
      req({ key: 'mounting', label: 'Mounting arrangement', termsAny: ['foot mounted', 'flange mounted', 'b3', 'b5', 'b35', 'v1', 'mounting'], severity: 'WARNING', whyItMatters: 'Mounting must suit the driven machine.', suggestion: 'State the mounting (e.g. foot-mounted B3).' }),
      req({ key: 'enclosure', label: 'Enclosure protection and cooling', quantityKinds: ['IP_RATING'], termsAny: ['tefc', 'ic 411', 'ic411'], severity: 'WARNING', whyItMatters: 'The site environment determines the required enclosure and cooling method.', suggestion: 'State the degree of protection (e.g. IP55) and cooling method (e.g. TEFC, IC 411).' }),
      req({ key: 'insulation_class', label: 'Insulation class', termsAny: ['class f', 'class b', 'class h', 'insulation class'], severity: 'INFO', whyItMatters: 'Insulation class sets thermal margins.', suggestion: 'State insulation class and permitted temperature rise (e.g. class F, rise limited to class B).' }),
      req({ key: 'starting', label: 'Starting method', termsAny: ['dol', 'direct on line', 'star delta', 'star-delta', 'vfd', 'soft starter', 'inverter duty'], severity: 'INFO', whyItMatters: 'Starting method affects motor design and supply disturbance.', suggestion: 'State the starting method (DOL, star-delta, VFD).' }),
      ambient,
      quantity,
      warranty,
    ],
    templateSource: 'Template curated by FiiSpec from the parameters addressed by IS 12615 and IS/IEC 60034-1. Benchmark data — not an official checklist.',
    lifecycle: 'PUBLISHED',
  },
  {
    id: 'submersible-pumpset',
    label: 'Submersible pumpset (borewell)',
    sector: 'MECHANICAL',
    aliases: ['submersible pump', 'submersible pumpset', 'submersible pump set', 'borewell pump', 'bore well pump', 'borewell submersible', 'submersible motor pump', 'tubewell pump'],
    description: 'Submersible pumpsets for borewells, for irrigation and water supply.',
    requiresInstallation: true,
    parameterTemplate: [
      req({ key: 'discharge', label: 'Rated discharge (flow)', quantityKinds: ['FLOW_RATE'], termsAny: ['discharge'], severity: 'CRITICAL', whyItMatters: 'Discharge at the duty point is the primary performance requirement tested at acceptance (IS 11346).', suggestion: 'State rated discharge (e.g. 18 m³/h or 300 lpm) at the rated head.', relatedStandardIds: ['is-11346'] }),
      req({ key: 'head', label: 'Rated total head', quantityKinds: ['HEAD'], severity: 'CRITICAL', whyItMatters: 'Head and discharge together define the duty point.', suggestion: 'State the rated total head in metres and the operating head range.' }),
      req({ key: 'motor_rating', label: 'Motor rating', quantityKinds: ['POWER'], severity: 'CRITICAL', whyItMatters: 'Motor rating must suit the duty point and supply (IS 9283).', suggestion: 'State motor rating in kW (HP may be stated additionally).', relatedStandardIds: ['is-9283'] }),
      req({ key: 'supply', label: 'Supply voltage and phases', quantityKinds: ['VOLTAGE', 'PHASE'], severity: 'CRITICAL', whyItMatters: 'Rural supplies may be single-phase or three-phase with wide voltage variation.', suggestion: 'State supply voltage, phases and the voltage range the pumpset must operate over.' }),
      req({ key: 'bore_size', label: 'Borewell size', termsAny: ['mm bore', 'mm borewell', 'bore size', 'borewell size', 'inch bore', 'bore diameter'], severity: 'CRITICAL', whyItMatters: 'The pumpset must physically fit the borewell.', suggestion: 'State the minimum borewell inside diameter (e.g. 150 mm).' }),
      req({ key: 'efficiency', label: 'Minimum pumpset efficiency', quantityKinds: ['EFFICIENCY'], termsAny: ['overall efficiency', 'pumpset efficiency'], severity: 'WARNING', whyItMatters: 'Efficiency determines lifetime energy cost for the farmer or utility.', suggestion: 'State minimum overall efficiency at the duty point.' }),
      req({ key: 'materials', label: 'Material of construction', termsAny: ['stainless steel', 'cast iron', 'noryl', 'bronze', 'impeller'], severity: 'INFO', whyItMatters: 'Water quality (sand, salinity) determines suitable materials.', suggestion: 'State materials for impellers, diffusers and shaft, or the water quality.' }),
      req({ key: 'cable', label: 'Drop cable and control panel', quantityKinds: ['CROSS_SECTION'], termsAny: ['cable', 'starter', 'control panel'], severity: 'INFO', whyItMatters: 'Cable size and starter/protection are needed for a complete installation.', suggestion: 'State drop cable size/length and starter or control panel requirements.' }),
      quantity,
      warranty,
    ],
    templateSource: 'Template curated by FiiSpec from the parameters addressed by IS 8034, IS 9283 and IS 11346. Benchmark data — not an official checklist.',
    lifecycle: 'PUBLISHED',
  },
  {
    id: 'monoset-pump',
    label: 'Monoset pump',
    sector: 'MECHANICAL',
    aliases: ['monoset pump', 'monoblock pump', 'mono set pump', 'mono block pump', 'centrifugal monoblock', 'monoblock pumpset'],
    description: 'Electric monoset (monoblock) pumps for clear, cold water.',
    requiresInstallation: false,
    parameterTemplate: [
      req({ key: 'discharge', label: 'Rated discharge', quantityKinds: ['FLOW_RATE'], termsAny: ['discharge'], severity: 'CRITICAL', whyItMatters: 'Duty point performance is the core acceptance criterion.', suggestion: 'State rated discharge at the rated head.', relatedStandardIds: ['is-11346'] }),
      req({ key: 'head', label: 'Rated total head', quantityKinds: ['HEAD'], severity: 'CRITICAL', whyItMatters: 'Head defines the duty point.', suggestion: 'State the rated total head in metres.' }),
      req({ key: 'motor_rating', label: 'Motor rating', quantityKinds: ['POWER'], severity: 'CRITICAL', whyItMatters: 'Motor rating must suit the duty point.', suggestion: 'State motor rating in kW.' }),
      req({ key: 'supply', label: 'Supply voltage and phases', quantityKinds: ['VOLTAGE', 'PHASE'], severity: 'CRITICAL', whyItMatters: 'Motor must match the available supply.', suggestion: 'State supply voltage and phases.' }),
      quantity,
    ],
    templateSource: 'Template curated by FiiSpec from IS 9079 and IS 11346. Benchmark data.',
    lifecycle: 'PUBLISHED',
  },
  {
    id: 'openwell-submersible',
    label: 'Openwell submersible pumpset',
    sector: 'MECHANICAL',
    aliases: ['openwell submersible', 'open well submersible', 'openwell pump', 'open well pump', 'openwell pumpset'],
    description: 'Submersible pumpsets for open wells.',
    requiresInstallation: true,
    parameterTemplate: [
      req({ key: 'discharge', label: 'Rated discharge', quantityKinds: ['FLOW_RATE'], termsAny: ['discharge'], severity: 'CRITICAL', whyItMatters: 'Duty point performance is the core acceptance criterion.', suggestion: 'State rated discharge at the rated head.', relatedStandardIds: ['is-11346'] }),
      req({ key: 'head', label: 'Rated total head', quantityKinds: ['HEAD'], severity: 'CRITICAL', whyItMatters: 'Head defines the duty point.', suggestion: 'State the rated total head in metres.' }),
      req({ key: 'motor_rating', label: 'Motor rating', quantityKinds: ['POWER'], severity: 'CRITICAL', whyItMatters: 'Motor rating must suit the duty point.', suggestion: 'State motor rating in kW.' }),
      quantity,
    ],
    templateSource: 'Template curated by FiiSpec from IS 14220 and IS 11346. Benchmark data.',
    lifecycle: 'PUBLISHED',
  },
  {
    id: 'centrifugal-pump',
    label: 'Horizontal centrifugal pump',
    sector: 'MECHANICAL',
    aliases: ['horizontal centrifugal pump', 'centrifugal pump', 'end suction pump'],
    description: 'Horizontal centrifugal pumps for clear, cold water.',
    requiresInstallation: false,
    parameterTemplate: [
      req({ key: 'discharge', label: 'Rated discharge', quantityKinds: ['FLOW_RATE'], termsAny: ['discharge'], severity: 'CRITICAL', whyItMatters: 'Duty point performance is the core acceptance criterion.', suggestion: 'State rated discharge at the rated head.', relatedStandardIds: ['is-11346'] }),
      req({ key: 'head', label: 'Rated total head', quantityKinds: ['HEAD'], severity: 'CRITICAL', whyItMatters: 'Head defines the duty point.', suggestion: 'State the rated total head in metres.' }),
      quantity,
    ],
    templateSource: 'Template curated by FiiSpec from IS 6595 (Part 1) and IS 11346. Benchmark data.',
    lifecycle: 'PUBLISHED',
  },
  {
    id: 'portland-cement',
    label: 'Ordinary Portland cement',
    sector: 'CIVIL_CONSTRUCTION',
    aliases: ['ordinary portland cement', 'opc', 'opc 33', 'opc 43', 'opc 53', '33 grade cement', '43 grade cement', '53 grade cement', 'cement', 'portland cement'],
    description: 'Ordinary Portland cement (33, 43 and 53 grades) for general construction.',
    requiresInstallation: false,
    parameterTemplate: [
      req({ key: 'grade', label: 'Cement grade', quantityKinds: ['GRADE'], severity: 'CRITICAL', whyItMatters: 'IS 269 covers 33, 43 and 53 grades with different strength requirements.', suggestion: 'State the grade (e.g. OPC 43) as per IS 269.', relatedStandardIds: ['is-269'] }),
      req({ key: 'quantity', label: 'Quantity', quantityKinds: ['QUANTITY', 'MASS'], termsAny: ['bags', 'mt', 'tonnes'], severity: 'CRITICAL', whyItMatters: 'Quantity drives price and delivery schedule.', suggestion: 'State the total quantity (tonnes or number of 50 kg bags).' }),
      req({ key: 'packaging', label: 'Packaging and delivery', termsAny: ['bag', 'bags', 'bulk', 'packing', 'packed'], severity: 'WARNING', whyItMatters: 'Packaging affects handling, storage and sampling.', suggestion: 'State packaging (e.g. 50 kg bags) and delivery schedule/location.' }),
      req({ key: 'test_certificate', label: 'Manufacturer’s test certificate', termsAny: ['test certificate', 'manufacturer test certificate', 'mtc', 'test report'], severity: 'WARNING', whyItMatters: 'Test certificates per consignment are the primary conformity evidence.', suggestion: 'Require the manufacturer’s test certificate for each consignment, with test results as per IS 4031 / IS 4032.', relatedStandardIds: ['is-4031', 'is-4032'] }),
      req({ key: 'age', label: 'Maximum age at delivery', termsAny: ['not older than', 'week of manufacture', 'date of manufacture', 'age of cement', 'freshness'], severity: 'WARNING', whyItMatters: 'Cement loses strength with storage time.', suggestion: 'State the maximum age of cement at delivery (e.g. not older than a stated number of weeks).' }),
    ],
    templateSource: 'Template curated by FiiSpec from the requirements addressed by IS 269, IS 4031 and IS 4032. Benchmark data — not an official checklist.',
    lifecycle: 'PUBLISHED',
  },
  {
    id: 'ppc-cement',
    label: 'Portland pozzolana cement',
    sector: 'CIVIL_CONSTRUCTION',
    parentId: 'portland-cement',
    aliases: ['portland pozzolana cement', 'ppc', 'fly ash cement', 'pozzolana cement', 'ppc cement'],
    description: 'Fly ash based Portland pozzolana cement.',
    requiresInstallation: false,
    parameterTemplate: [
      req({ key: 'quantity', label: 'Quantity', quantityKinds: ['QUANTITY', 'MASS'], termsAny: ['bags', 'mt', 'tonnes'], severity: 'CRITICAL', whyItMatters: 'Quantity drives price and delivery schedule.', suggestion: 'State the total quantity.' }),
      req({ key: 'test_certificate', label: 'Manufacturer’s test certificate', termsAny: ['test certificate', 'mtc', 'test report'], severity: 'WARNING', whyItMatters: 'Test certificates are the primary conformity evidence.', suggestion: 'Require test certificates per consignment.', relatedStandardIds: ['is-4031', 'is-4032'] }),
    ],
    templateSource: 'Template curated by FiiSpec from IS 1489 (Part 1). Benchmark data.',
    lifecycle: 'PUBLISHED',
  },
  {
    id: 'tmt-bars',
    label: 'Reinforcement steel (TMT bars)',
    sector: 'CIVIL_CONSTRUCTION',
    aliases: ['tmt bar', 'tmt bars', 'tmt', 'reinforcement steel', 'reinforcement bars', 'rebar', 'rebars', 'deformed steel bars', 'hysd bars', 'hsd bars', 'fe 500', 'fe500', 'fe 500d', 'fe500d', 'fe 550', 'fe 415'],
    description: 'High strength deformed steel bars for concrete reinforcement.',
    requiresInstallation: false,
    parameterTemplate: [
      req({ key: 'grade', label: 'Steel grade', quantityKinds: ['GRADE'], severity: 'CRITICAL', whyItMatters: 'IS 1786 grades (e.g. Fe 500D) have different strength and ductility requirements.', suggestion: 'State the grade (e.g. Fe 500D) as per IS 1786.', relatedStandardIds: ['is-1786'] }),
      req({ key: 'diameter', label: 'Bar diameters', termsAny: ['mm dia', 'diameter', 'dia', 'mm bars', 'mm to'], severity: 'CRITICAL', whyItMatters: 'Diameters and their quantities define the order.', suggestion: 'List nominal diameters with quantity per diameter.' }),
      req({ key: 'quantity', label: 'Quantity', quantityKinds: ['QUANTITY', 'MASS'], termsAny: ['mt', 'tonnes'], severity: 'CRITICAL', whyItMatters: 'Quantity drives price and delivery schedule.', suggestion: 'State the total quantity in tonnes.' }),
      req({ key: 'test_certificate', label: 'Mill test certificate', termsAny: ['test certificate', 'mill test', 'mtc', 'test report'], severity: 'WARNING', whyItMatters: 'Test certificates demonstrate tensile, bend and chemical properties.', suggestion: 'Require mill test certificates per heat/lot, with tensile tests as per IS 1608 (Part 1).', relatedStandardIds: ['is-1608-1'] }),
      req({ key: 'length', label: 'Supply length', termsAny: ['length', '12 m', '12 metre'], severity: 'INFO', whyItMatters: 'Bar length affects wastage and transport.', suggestion: 'State the supply length (e.g. 12 m) and tolerance.' }),
    ],
    templateSource: 'Template curated by FiiSpec from IS 1786 and IS 1608 (Part 1). Benchmark data — not an official checklist.',
    lifecycle: 'PUBLISHED',
  },
  {
    id: 'structural-steel',
    label: 'Structural steel',
    sector: 'CIVIL_CONSTRUCTION',
    aliases: ['structural steel', 'hot rolled steel', 'steel plates', 'steel sections', 'ms plate', 'ms plates', 'ms angle', 'ms channel', 'steel beams', 'e250', 'e350'],
    description: 'Hot rolled structural steel plates and sections.',
    requiresInstallation: false,
    parameterTemplate: [
      req({ key: 'grade', label: 'Steel grade', termsAny: ['e250', 'e350', 'e410', 'e450', 'grade'], severity: 'CRITICAL', whyItMatters: 'Grade defines strength and weldability.', suggestion: 'State the grade (e.g. E250 BR) as per IS 2062.', relatedStandardIds: ['is-2062'] }),
      req({ key: 'quantity', label: 'Quantity', quantityKinds: ['QUANTITY', 'MASS'], termsAny: ['mt', 'tonnes'], severity: 'CRITICAL', whyItMatters: 'Quantity drives price.', suggestion: 'State quantities per section/thickness.' }),
    ],
    templateSource: 'Template curated by FiiSpec from IS 2062. Benchmark data.',
    lifecycle: 'PUBLISHED',
  },
  {
    id: 'concrete-works',
    label: 'Plain and reinforced concrete works',
    sector: 'CIVIL_CONSTRUCTION',
    aliases: ['reinforced concrete', 'rcc', 'plain concrete', 'pcc', 'concrete work', 'concrete works', 'ready mix concrete', 'ready mixed concrete', 'rmc', 'm20 concrete', 'm25 concrete', 'm30 concrete'],
    description: 'Plain and reinforced cement concrete construction.',
    requiresInstallation: true,
    parameterTemplate: [
      req({ key: 'concrete_grade', label: 'Concrete grade', quantityKinds: ['GRADE'], severity: 'CRITICAL', whyItMatters: 'Concrete grade defines characteristic strength and mix design.', suggestion: 'State the concrete grade (e.g. M25) as per IS 456.', relatedStandardIds: ['is-456'] }),
      req({ key: 'exposure', label: 'Exposure condition', termsAny: ['exposure', 'mild', 'moderate', 'severe', 'very severe', 'extreme'], severity: 'WARNING', whyItMatters: 'IS 456 durability requirements depend on the exposure condition.', suggestion: 'State the exposure condition (mild to extreme).' }),
      req({ key: 'cement_type', label: 'Cement type', termsAny: ['opc', 'ppc', 'cement'], severity: 'WARNING', whyItMatters: 'Cement type affects durability and setting.', suggestion: 'State permitted cement types (e.g. OPC to IS 269 or PPC to IS 1489 (Part 1)).', relatedStandardIds: ['is-269', 'is-1489-1'] }),
    ],
    templateSource: 'Template curated by FiiSpec from IS 456. Benchmark data.',
    lifecycle: 'PUBLISHED',
  },
  {
    id: 'aggregates',
    label: 'Aggregates for concrete',
    sector: 'CIVIL_CONSTRUCTION',
    aliases: ['coarse aggregate', 'fine aggregate', 'aggregates', 'aggregate', 'crushed stone', 'river sand', 'manufactured sand', 'm-sand'],
    description: 'Coarse and fine aggregates for concrete.',
    requiresInstallation: false,
    parameterTemplate: [
      req({ key: 'size', label: 'Nominal size / grading zone', termsAny: ['mm', 'zone', 'grading'], severity: 'CRITICAL', whyItMatters: 'Grading determines workability and strength.', suggestion: 'State nominal size or grading zone as per IS 383.', relatedStandardIds: ['is-383'] }),
      quantity,
    ],
    templateSource: 'Template curated by FiiSpec from IS 383. Benchmark data.',
    lifecycle: 'PUBLISHED',
  },
  {
    id: 'pvc-cable',
    label: 'PVC insulated building wire',
    sector: 'ELECTRICAL',
    aliases: ['pvc cable', 'pvc insulated cable', 'pvc wire', 'house wire', 'house wiring cable', 'building wire', 'flexible cable', 'flexible cord', 'fr wire', 'frls wire', 'copper wire'],
    description: 'PVC insulated wires and flexible cords for building wiring.',
    requiresInstallation: false,
    parameterTemplate: [
      req({ key: 'conductor_size', label: 'Conductor size', quantityKinds: ['CROSS_SECTION'], severity: 'CRITICAL', whyItMatters: 'Conductor size determines current capacity and voltage drop.', suggestion: 'State conductor cross-section in mm².' }),
      req({ key: 'conductor_material', label: 'Conductor material and class', termsAny: ['copper', 'aluminium', 'aluminum', 'class 2', 'class 5', 'flexible'], severity: 'CRITICAL', whyItMatters: 'Conductor material and flexibility class affect performance and price.', suggestion: 'State conductor material and class (e.g. copper, class 5 flexible).' }),
      req({ key: 'voltage_grade', label: 'Voltage grade', quantityKinds: ['VOLTAGE'], severity: 'WARNING', whyItMatters: 'Voltage grade must match the installation.', suggestion: 'State the voltage grade (e.g. 450/750 V).' }),
      req({ key: 'fire_performance', label: 'Fire performance', termsAny: ['fr', 'frls', 'flame retardant', 'low smoke', 'halogen free', 'zhfr'], severity: 'INFO', whyItMatters: 'Fire performance matters for public buildings and escape routes.', suggestion: 'State fire performance requirements (e.g. FR-LSH) where needed.' }),
      req({ key: 'quantity', label: 'Quantity (length)', quantityKinds: ['QUANTITY', 'LENGTH'], termsAny: ['coils', 'metres', 'meters', 'km'], severity: 'CRITICAL', whyItMatters: 'Quantity drives price.', suggestion: 'State total length per size (coils of 90 m, or metres).' }),
    ],
    templateSource: 'Template curated by FiiSpec from IS 694. Benchmark data.',
    lifecycle: 'PUBLISHED',
  },
  {
    id: 'power-cable',
    label: 'LV power cable (up to 1.1 kV)',
    sector: 'ELECTRICAL',
    aliases: ['xlpe cable', 'xlpe power cable', 'power cable', 'armoured cable', 'armored cable', 'lt cable', 'lt power cable', '1.1 kv cable', '1100 v cable', 'underground cable', 'pvc power cable'],
    description: 'PVC or XLPE insulated power cables for working voltages up to 1.1 kV.',
    requiresInstallation: true,
    parameterTemplate: [
      req({ key: 'insulation', label: 'Insulation type', termsAny: ['xlpe', 'pvc'], severity: 'CRITICAL', whyItMatters: 'Insulation type decides the applicable standard (IS 7098 (Part 1) or IS 1554 (Part 1)).', suggestion: 'State the insulation (XLPE or PVC).', relatedStandardIds: ['is-7098-1', 'is-1554-1'] }),
      req({ key: 'cores_size', label: 'Number of cores and conductor size', quantityKinds: ['CROSS_SECTION'], termsAny: ['core', 'cores'], severity: 'CRITICAL', whyItMatters: 'Cores and cross-section define current capacity.', suggestion: 'State cores × size (e.g. 3.5C × 95 mm²).' }),
      req({ key: 'conductor_material', label: 'Conductor material', termsAny: ['copper', 'aluminium', 'aluminum'], severity: 'CRITICAL', whyItMatters: 'Conductor material affects rating and price.', suggestion: 'State copper or aluminium conductor.' }),
      req({ key: 'armour', label: 'Armouring', termsAny: ['armoured', 'armored', 'unarmoured', 'unarmored', 'strip armour', 'wire armour'], severity: 'WARNING', whyItMatters: 'Armour is needed for direct burial and mechanical protection.', suggestion: 'State armoured/unarmoured and armour type.' }),
      req({ key: 'quantity', label: 'Quantity (length)', quantityKinds: ['QUANTITY', 'LENGTH'], termsAny: ['metres', 'meters', 'km', 'drum'], severity: 'CRITICAL', whyItMatters: 'Quantity drives price.', suggestion: 'State length per size and drum lengths.' }),
    ],
    templateSource: 'Template curated by FiiSpec from IS 7098 (Part 1) and IS 1554 (Part 1). Benchmark data.',
    lifecycle: 'PUBLISHED',
  },
  {
    id: 'distribution-transformer',
    label: 'Distribution transformer',
    sector: 'ELECTRICAL',
    aliases: ['distribution transformer', 'oil immersed transformer', 'oil-immersed transformer', 'oil filled transformer', 'kva transformer', '11 kv transformer', '33 kv transformer', 'pole mounted transformer'],
    description: 'Outdoor oil-immersed distribution transformers up to 2 500 kVA, 33 kV.',
    requiresInstallation: true,
    parameterTemplate: [
      req({ key: 'rating', label: 'Rated power (kVA)', quantityKinds: ['APPARENT_POWER'], severity: 'CRITICAL', whyItMatters: 'kVA rating defines the transformer and its efficiency/loss requirements.', suggestion: 'State the rating in kVA.' }),
      req({ key: 'voltage_ratio', label: 'Voltage ratio', quantityKinds: ['VOLTAGE'], severity: 'CRITICAL', whyItMatters: 'Primary and secondary voltages must match the network.', suggestion: 'State the voltage ratio (e.g. 11 kV / 433 V).' }),
      req({ key: 'energy_efficiency_level', label: 'Energy efficiency level / star rating', quantityKinds: ['EFFICIENCY_CLASS'], termsAny: ['energy efficiency level', 'star', 'maximum losses', 'total losses'], severity: 'CRITICAL', whyItMatters: 'IS 1180 (Part 1) specifies energy efficiency levels, and BEE star labelling for distribution transformers is listed as mandatory.', suggestion: 'State the required energy efficiency level or BEE star rating and maximum total losses.', relatedStandardIds: ['is-1180-1'] }),
      req({ key: 'vector_group', label: 'Vector group', termsAny: ['vector group', 'dyn11', 'dyn 11'], severity: 'WARNING', whyItMatters: 'Vector group must suit the network.', suggestion: 'State the vector group (e.g. Dyn11).' }),
      req({ key: 'cooling', label: 'Cooling', termsAny: ['onan', 'cooling'], severity: 'INFO', whyItMatters: 'Cooling class affects rating.', suggestion: 'State cooling (e.g. ONAN).' }),
      req({ key: 'tapping', label: 'Tapping range', termsAny: ['tap', 'tapping', 'off-circuit tap', 'oltc'], severity: 'WARNING', whyItMatters: 'Tapping range allows voltage regulation.', suggestion: 'State tapping range and type.' }),
      quantity,
    ],
    templateSource: 'Template curated by FiiSpec from IS 1180 (Part 1). Benchmark data — not an official checklist.',
    lifecycle: 'PUBLISHED',
  },
  {
    id: 'protection-devices',
    label: 'Circuit protection devices (MCB/RCCB/RCBO)',
    sector: 'ELECTRICAL',
    aliases: ['mcb', 'mcbs', 'rccb', 'rccbs', 'rcbo', 'rcbos', 'miniature circuit breaker', 'residual current circuit breaker', 'circuit breaker', 'elcb'],
    description: 'Miniature circuit-breakers and residual current devices for household and similar installations.',
    requiresInstallation: false,
    parameterTemplate: [
      req({ key: 'rated_current', label: 'Rated current', quantityKinds: ['CURRENT'], severity: 'CRITICAL', whyItMatters: 'Rated current must match the protected circuit.', suggestion: 'State rated current (A).' }),
      req({ key: 'poles', label: 'Number of poles', termsAny: ['sp', 'dp', 'tp', 'tpn', 'fp', 'pole', 'poles', '2p', '4p'], severity: 'CRITICAL', whyItMatters: 'Pole configuration must match the supply.', suggestion: 'State number of poles (e.g. DP, TPN, 4P).' }),
      req({ key: 'breaking_capacity', label: 'Breaking capacity / tripping characteristic', termsAny: ['breaking capacity', 'ka', 'c curve', 'b curve', 'curve'], severity: 'WARNING', whyItMatters: 'Breaking capacity must exceed the prospective fault current.', suggestion: 'State breaking capacity (kA) and tripping curve.' }),
      req({ key: 'sensitivity', label: 'Residual current sensitivity (for RCDs)', termsAny: ['30 ma', '100 ma', '300 ma', 'sensitivity', 'type a', 'type ac', 'type b'], severity: 'WARNING', whyItMatters: 'Sensitivity and RCD type determine protection level.', suggestion: 'State rated residual operating current and RCD type.' }),
      quantity,
    ],
    templateSource: 'Template curated by FiiSpec from IS/IEC 60898-1 and IS 12640. Benchmark data.',
    lifecycle: 'PUBLISHED',
  },
  {
    id: 'electrical-installation',
    label: 'Electrical wiring and earthing installation',
    sector: 'ELECTRICAL',
    aliases: ['electrical wiring', 'wiring installation', 'internal wiring', 'internal electrification', 'electrical installation', 'earthing', 'earthing system', 'earth pit', 'earthing work'],
    description: 'Design and execution of electrical wiring and earthing installations.',
    requiresInstallation: true,
    parameterTemplate: [
      req({ key: 'scope', label: 'Installation scope', termsAny: ['points', 'circuits', 'distribution board', 'db'], severity: 'CRITICAL', whyItMatters: 'Scope must be defined for pricing and acceptance.', suggestion: 'Define the installation scope (points, circuits, distribution boards).' }),
      req({ key: 'earth_resistance', label: 'Earth resistance requirement', termsAny: ['earth resistance', 'ohm', 'ohms'], severity: 'WARNING', whyItMatters: 'A target earth resistance is needed for acceptance testing.', suggestion: 'State the maximum earth resistance and test method as per IS 3043.', relatedStandardIds: ['is-3043'] }),
    ],
    templateSource: 'Template curated by FiiSpec from IS 732 and IS 3043. Benchmark data.',
    lifecycle: 'PUBLISHED',
  },
  {
    id: 'li-ion-battery',
    label: 'Lithium-ion battery',
    sector: 'ELECTRONICS_IT',
    aliases: ['lithium ion battery', 'lithium-ion battery', 'li-ion battery', 'li ion battery', 'lithium battery', 'lithium cell', 'battery pack', 'lifepo4'],
    description: 'Portable sealed secondary lithium cells and batteries.',
    requiresInstallation: false,
    parameterTemplate: [
      req({ key: 'capacity', label: 'Rated capacity', quantityKinds: ['CAPACITY_AH', 'ENERGY'], severity: 'CRITICAL', whyItMatters: 'Capacity defines the battery.', suggestion: 'State rated capacity (Ah or kWh).' }),
      req({ key: 'voltage', label: 'Nominal voltage', quantityKinds: ['VOLTAGE'], severity: 'CRITICAL', whyItMatters: 'Nominal voltage must match the equipment.', suggestion: 'State nominal voltage.' }),
      req({ key: 'chemistry', label: 'Cell chemistry', termsAny: ['lfp', 'lifepo4', 'nmc', 'lithium iron phosphate', 'chemistry'], severity: 'WARNING', whyItMatters: 'Chemistry affects safety, life and cost.', suggestion: 'State the cell chemistry.' }),
      quantity,
    ],
    templateSource: 'Template curated by FiiSpec from IS 16046 (Part 2). Benchmark data.',
    lifecycle: 'PUBLISHED',
  },
  {
    id: 'solar-pv-module',
    label: 'Solar PV module',
    sector: 'RENEWABLE_ENERGY',
    aliases: ['solar panel', 'solar panels', 'solar module', 'solar modules', 'pv module', 'pv modules', 'photovoltaic module', 'solar pv', 'mono perc', 'bifacial module'],
    description: 'Terrestrial crystalline silicon photovoltaic modules.',
    requiresInstallation: true,
    parameterTemplate: [
      req({ key: 'rated_power', label: 'Rated peak power per module', quantityKinds: ['POWER'], termsAny: ['wp'], severity: 'CRITICAL', whyItMatters: 'Module power rating defines the array design.', suggestion: 'State rated peak power (Wp) and tolerance.' }),
      req({ key: 'efficiency', label: 'Module efficiency', quantityKinds: ['EFFICIENCY'], severity: 'WARNING', whyItMatters: 'Efficiency affects land/roof area needed.', suggestion: 'State minimum module efficiency.' }),
      req({ key: 'technology', label: 'Cell technology', termsAny: ['mono', 'monocrystalline', 'polycrystalline', 'perc', 'topcon', 'bifacial'], severity: 'INFO', whyItMatters: 'Technology affects performance and degradation.', suggestion: 'State cell technology if relevant.' }),
      warranty,
      quantity,
    ],
    templateSource: 'Template curated by FiiSpec from IS 14286 and IS/IEC 61730. Benchmark data.',
    lifecycle: 'PUBLISHED',
  },
];
